import uuid
from app.database import SessionLocal, engine, Base
from app.models.models import KMSParameter

def seed_parameters():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    
    # Clear existing data to avoid duplicates
    db.query(KMSParameter).delete()
    
    # Data Karakter (40)
    karakter_data = [
        ("3 Tujuan Penciptaan Manusia", "Memiliki tujuan hidup", "Allah Swt tidak menciptakan manusia hanya untuk main-main, Allah menciptakan manusia dengan tujuan hadiah dan hukuman. Apabila tujuan itu dapat dicapai oleh manusia maka akan diganjar dengan hadiah surga. Apabila tujuan itu tidak tercapai, maka akan diganjar dengan neraka."),
        ("3 Tujuan Penciptaan Manusia", "Mampu memimpin & dipimpin", "Tujuan penciptaan yang pertama adalah menjadi pemimpin (khalifah). Dan tak mungkin bisa menjadi pemimpin apabila tidak bisa dipimpin."),
        ("3 Tujuan Penciptaan Manusia", "Mampu mengatur diri & waktu dengan baik.", "Tujuan penciptaan yang Allah canangkan tidak mungkin akan dapat dicapai oleh manusia apabila manusia itu tidak bisa mengatur diri dan waktunya dengan baik."),
        ("3 Tujuan Penciptaan Manusia", "Terlibat dalam kehidupan sosial & suka membantu", "“Tujuan penciptaan manusia adalah ; agar manusia menjadi pemimpin, agar manusia menegakkan ibadah, agar manusia menjadi bermanfaat (terutama sebagai Ahlul Quran). Tujuan penciptaan yang ketiga ( agar manusia menjadi bermanfaat ) hanya mungkin diraih dengan cara terlibat dengan kehidupan sosial dan memberikan manfaat bagi orang lain dan masyarakat.”"),
        ("3 Tujuan Penciptaan Manusia", "Konsisten ibadahnya & memiliki hubungan yang kuat dengan Al-Quran", "Apabila manusia tidak beribadah, maka jelas 1 tujuan penciptaan gagal ia raih. Apabila manusia tidak punya interaksi dengan Al-Quran (tidak bisa membaca, menghafal, memahami, mengamalkan, dan mengajarkannya) maka ia akan gagal mencapai 1 tujuan penciptaan yang Allah taala canangkan."),
        ("3 Alat Belajar Manusia", "Rasa ingin tahunya besar & gemar membaca", "“Belajar” adalah perintah pertama yang turun melalui ayat QS Al-Alaq ayat 1-5. Ini membuktikan bahwa manusia hanya akan sukses apabila ia gemar membaca. Semakin banyak yang ia baca maka akan semakin kaya ia dengan pertanyaan-pertanyaan. Dan ciri manusia cerdas adalah “Banyak bertanya.” atau “Punya rasa ingin tahu yang besar.”"),
        ("3 Alat Belajar Manusia", "Berpikiran terbuka & suka mencoba hal baru.", "Manusia yang menjalankan perintah Allah yang pertama. Akan Allah Swt jadikan ia bermindset yang growth and open mind. Dengan begitu ia akan punya peluang besar untuk menjadi orang yang maksimal kecerdasan kognitifnya, emotionalnya, dan spiritualnya. Fisiknya sehat, mentalnya hebat, softskillnya indah, and karakternya Quranik. Isya Allah bukan hanya pikiran and perkataannya, tetapi juga perbuatannya."),
        ("3 Alat Belajar Manusia", "Imajinasinya kaya (Sumber K2IAM)", "Awalnya semua manusia pandai menghayal, semestinya ini adalah pondasi dari kreativitas, inovasi, and antisipatif. Namun sayang kebanyakan manusia membunuh kemampuan ini sejak dini. Bagaimana mereka membunuh potensi-potensi hebat ini ? Dengan menggunakan telinga mata and hatinya untuk hiburan and bermaksiat, bukan untuk membaca and mempertajam rasa ingin tahunya."),
        ("3 Alat Belajar Manusia", "Berjuang memfilter 3 alat belajar.", "Manusia yang banyak membaca, ia akan kaya dengan pengetahuan, kaya wawasannya, pikirannya besar, tinggi cita-citanya. Dan manusia yang seperti itu akan mudah memahami tentang Tuhan and nilai-nilai agung agama. Dan manusia yang seperti itu akan semakin takut kepada Allah, and akan semakin berhati-hati terhadap apa yang ia dengar, lihat, and rasa."),
        ("Sumber kejahatan", "Menjadikan Islam sebagai identitas diri yang utama.", "Sumber kejahatan manusia adalah hawa nafsu and syaithan. Untuk menghadapi dua bahaya ini, manusia butuh nilai yang agung (Agama). Dan itulah fungsi yang utama dari agama, yaitu mengenalkan Tuhan and mengenalkan tentang kebenaran, pahala, and dosa. Maka keterikatan dengan agama merupakan syarat mutlak. Seharusnya manusia bangga dengan agama and agama harusnya menjadi identitas dirinya. Misalnya “Kenalkan nama saya purwanto and saya seorang muslim”. Manusia yang bahkan ‘malu’ dengan keislamannya, ia akan dekat dengan syaithan and ia akan gampang kalah dengan hawa nafsunya."),
        ("Sumber kejahatan", "Menjadikan Islam sebagai sumber kebenaran.", "Agama Islam adalah patokan atau rujukan dari semua nilai. Termasuk nilai”Benar’ and “Salah”. Manusia yang menjadikan agama sebagai sumber kebenaran, isya Allah tidak akan kebingungan. Berbeda dengan orang yang mengambil kebenaran dari selain agama, ia akan bingung dengan pertentangan yang banyak antara kebenaran yang pragmatis, bisa berbeda dengan kebenaran konsensus, atau bahkan mengambil pikiran manusia yang berbeda-beda standarnya, apalagi mengambil dari budaya manusia yang berbagai macam."),
        ("Sumber kejahatan", "Menjadikan Islam as panduan dalam berpikir, berkata, & bertindak.", "Seorang mukmin yang taat and patuh kepada Islam tentu akan menjadikan Al-Quran as petunjuk untuk berpikir berucap and bertindak. Hidup seorang mukmin diatur sepenuhnya oleh Islam."),
        ("Sumber kejahatan", "Berusaha keras untuk berbuat benar.", "“Manusia memang bukan malaikat yang pasti berbuat benar. Manusia Allah jadikan as mahluk yang bebas memilih, ia digoda oleh syaithan and hawa nafsunya. Oleh karena itulah, kadang manusia itu keliru, kadang salah, kadang bertentangan dengan agama.”Tetapi satu hal yang tak boleh hilang, yaitu keinginan untuk berbuat benar. Asalkan keinginan ini ada maka dosa and kesalahan sangat mungkin akan Allah ampuni."),
        ("Sumber kejahatan", "Berusaha keras mencegah dirinya berbuat salah.", "Manusia memang bukan malaikat yang pasti berbuat benar. Manusia Allah jadikan as mahluk yang bebas memilih, ia punya hawa nafsu and harus juga menghadapi godaan syaithan. Oleh karena itulah, kadang pilihan manusia itu keliru, kadang salah, kadang bertentangan dengan agama. Tetapi satu hal yang tak boleh hilang, yaitu keinginan untuk tidak berbuat salah. Asalkan keinginan ini ada maka manusia itu selalu diberi kesempatan oleh Allah untuk bertaubat."),
        ("Sumber kejahatan", "Memilih lingkungan & teman agar agama nya terjaga.", "Salah satu cara agar manusia selalu ingin berbuat benar, and selalu berusaha mencegah untuk berbuat salah… yaitu memilih lingkungan and teman yang membuat agama and moralnya terjaga."),
        ("Akhirat prioritas", "Menyadari bahwa dunia itu penting hanya karena itulah sat-satunya jalan menuju akhirat.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia sedang melakukan perjalanan yang panjang menuju dimensi akhirat. Dunia ini adalah halte, and tempat dimana manusia mendapatkan tiket menuju ke surga. Oleh karena itu manusia tidak boleh tersesat dengan apapun yang ada di dunia, seperti harta, jabatan, kesenangan, dsb. Sebab itu adalah godaan and ujian agar manusia melupakan akhirat and surga."),
        ("Akhirat prioritas", "Cita-cita, visi, and misinya dunia sekaligus akhirat.", "Berdasarkan pemahaman tentang kesementaraan dunia, and keabadian akhirat, maka seharusnya apapun yang dilakukan manusia, tujuannya bukan hanya untuk dunia ini. Tetapi harus juga bernilai ibadah. Maka mukmin yang memahami ini harus menjadikan cita-cita, visi, and misinya itu bernilai dunia sekaligus bernilai akhirat."),
        ("Akhirat prioritas", "Menjadikan Allah, Quran and Nabi Saw as prioritas yang lebih besar dari semua urusan.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia sedang melakukan perjalanan yang panjang menuju dimensi akhirat. Dunia ini adalah halte, and tempat dimana manusia mendapatkan tiket menuju ke surga. Tiket itu adalah ampunan Allah, cinta Allah and ridlo nya Allah. Dan itu hanya akan didapat apabila mukmin menjadikan Al-Quran as kitab petunjuk and menjadikan Nabi Muhammad as junjungan and tauladan yang utama. Maka dalam segala urusan, manusia harus merujuk kepada Islam agar tidak bertentangan dengan Allah Swt, Kitabullah, and Nabi Saw."),
        ("Makna ujian", "Memahami bahwa ujian adalah keniscayaan.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa and tangis. Yang paling terasa menyakitkan adalah ujian berbentuk tangis. Ini yang sering ditolak oleh manusia. Padahal tak mungkin menolak ujian. Ujian adalah keniscayaan. Pasti terjadi."),
        ("Makna ujian", "Memahami bahwa bentuk ujian itu berupa tawa & tangis.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa and tangis. Dua macam ujian ini sebenarnya membuat kita bisa bersabar and tangguh. Jangan terlalui senang, sebab di depan ada neraka. Tapi juga jangan terlalu sedih, sebab di depan ada surga."),
        ("Makna ujian", "Memahami bahwa ujian berupa tangis harus dijawab dengan jihad and sabar (terus berikhtiar).", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa and tangis. Menghadapi ujian berupa keburukan seperti musibah, kehilangan, kecelakaan, didzolimi orang, dsb. Manusia harus berjihad, yaitu terus berikhtiar. Tidak boleh menyerah and putus asa."),
        ("Makna ujian", "Memahami bahwa ujian berupa tawa harus dijawab dengan kendali diri, jangan sombong and bermaksiat.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa and tangis. Menghadapi ujian berupa kebaikan seperti fisik yang baik, rizqi melimpah, kemudahan, dsb. Manusia harus bersyukur and bersabar, wujud nyata (dari syukur and sabar) nya adalah tidak boleh sombong and bermaksiat."),
        ("Makna ujian", "Memahami bahwa ujian itu adalah peluang untuk berkembang.", "Apabila manusia jeli, maka akan jelaslah bahwa disetiap ujian terkandung peluang. Bayangkan ini seperti ujian sekolah yang kalau kita berhasil menyelesaikan dengan baik (nilainya tinggi) maka kita akan naik kelas. Dari SD menuju SMP, menuju SMA, menuju S1, S2, and S3. Itulah hakikat ujian as “Peluang untuk berkembang”."),
        ("Makna ujian", "Memiliki daya tahan yang baik terhadap tekanan, kesulitan, & stress.", "Semua ujian menuntut fokus and energi tambahan untuk menghadapinya. Manusia harus punya daya tahan terhadap tekanan, kesulitan, and stress. Kalau tidak, ia akan kalah, menyerah, and putus asa. Maka manusia harus berlatih and membangun daya tahan yang baik, sama seperti dunia gym. Kita tidak bisa langsung angkat barbel 100 kg, kita harus melatih diri dr 1 kg, menuju 2 kg, 3kg, 4 kg, dsb, dsb. Dari satu ujian ke ujian yang lain hakikatnya adalah “kita sedang berlatih.”"),
        ("Makna ujian", "Mampu menemukan hikmah dibalik ujian (baik di awal, di tengah, maupun di akhir)", "Apabila manusia jeli, maka akan jelaslah bahwa disetiap ujian terkandung hikmah. Bayangkan ini seperti ujian sekolah yang kita jalani. Di SD kita mendapatkan misalnya 10 ilmu, maka di SMP kita mendapat lebih banyak ilmu, di SMA semakin banyak, di universitas akan semakin banyak lagi, seperti itu terus-menerus. Maka ketika diuji jangan hanya fokus ke penderitaannya tapi fokus juga ke hikmah and manfaat yang kita dapat dari ujian itu. Baik di awal ujian, atau di tengah ujian, atau di akhir ujian."),
        ("Makna jihad", "Setia dengan tujuan & yakin bahwa tujuan itu akan tercapai.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani perjalanan menuju kesuksesan atau kegagalan. Baik kesuksesan dunia maupun kesuksesan akhirat. Kesuksesan akhirat itu adalah surga and melihat wajah Allah Taala. Sedangkan kesuksesan dunia lebih banyak bentuknya, misalnya kaya, jabatan, popularitas, dsb. Salah satu rahasia kesuksesan itu adalah “Merasa yakin, bahwa kita akan mendapatkan kesuksesan itu.” Dan setia with tujuan itu."),
        ("Makna jihad", "Memiliki endurance (kekuatan menderita) yang baik.", "Mukmin yang jeli akan mendapati sebuah kenyataan, bahwa di setiap ujian terdapat perjalanan. Ada yang pendek and ada yang panjang. Untuk perjalanan pendek itu bagaikan lomba lari jarak pendek, triknya hanyalah “Berlari sekuat tenaga, sekencang-kencangnya..” Tapi untuk perjalanan yang panjang seperti marathon, kita harus menjaga tenaga, jangan sampai kehabisan ditengah perjalanan. Harus diatur with baik agar sampai ke garis finish. Inilah yang disebut with endurance, yaitu konsisten mengatur energi hingga di garis finish."),
        ("Makna jihad", "Lebih terobsesi pada proses (ikhtiar) daripada hasil.", "Disetiap ujian ada yang namanya “hasil” and ada yang namanya “proses”. Mukmin sejati harus waspada, sebab di dalam ujian hasil akan tertolak apabila prosesnya keliru. Contoh, kalau kita mencontek di waktu ujian maka apabila dipergoki maka kita langsung dianggap gagal. Maka jangan hanya terobsesi pada hasil, tapi juga harus terobsesi pada kesempurnaan proses, artinya prosesnya harus bersih dari dosa."),
        ("Makna jihad", "Menerima kegagalan with baik & pandai mengambil hikmah untuk ikhtiar berikutnya.", "Disetiap ujian ada yang namanya berhasil ada yang namanya gagal. Di setiap tema ujian Allah mentaqdirkan beberapa kegagalan sebelum sampai pada kesuksesan. Maka jangan menyerah terhadap kegagalan, sebab setelah kegagalan itu pasti ada kesuksesan. Pelajari kegagalan itu, ambil hikmahnya, as catatan untuk memperbaiki ikhtiar yang berikutnya."),
        ("Makna taqdir", "Menerima masa lalu as taqdir Allah yang terbaik.", "Mukmin yang mempelajari Al-Quran akan tahu and paham tentang konsep takdir. Yaitu ketetapan yang Allah Al Khaliq gambarkan untuk manusia. Gambar ini berupa milyaran garis cerita untuk satu manusia, milyaran cerita itu walau variasi ceritanya bermilyar-milyar namun semua nya hanya with dua tujuan akhir, yaitu surga and neraka. Maka jangan meratapi masa lalu and jangan menyalahkan masa lalu, sebab apapun masa lalumu, itu adalah sebuah kebaikan menuju surgamu. Saya tidak menyalahkan orangtua saya yang miskin, saya tidak menyalahkan orangtua saya yang kafir, sebab justru itulah yang membuat saya kaya and menemukan Islam. Saya menerima masa lalu saya as masa lalu yang terbaik."),
        ("Makna taqdir", "Mengartikan masa depan as tanggung jawab pribadi.", "Mukmin yang baik dilarang menyalahkan masa lalu, and mukmin yang baik harus mengartikan masa depan as tanggung jawabnya pribadi. Percuma punya harta warisan yang banyak, sebab tanpa tanggung jawab and ilmu harta warisan itu bisa habis. Percuma punya orangtua profesor, walaupun kita punya dna nya tapi tanpa didukung with kerja keras, kita akan tetap bodoh juga. Apapun yang akan terjadi masa depan itu adalah tanggung jawabmu pribadi."),
        ("Makna taqdir", "Memahami bahwa manusia diberi hak untuk memilih & semua pilihan itu adalah taqdir Allah.", "Mukmin yang mempelajari Al-Quran akan tahu and paham tentang konsep takdir. Yaitu ketetapan yang Allah Al Khaliq gambarkan untuk manusia. Gambar ini berupa milyaran garis cerita untuk satu manusia, milyaran cerita itu walau variasi ceritanya bermilyar-milyar namun semua nya hanya with dua tujuan akhir, yaitu surga and neraka. Mukmin yang cerdas juga paham bahwa Allah memberikan hak pilih kepada manusia. Apa sebenarnya yang dipilih ? Jawabnya adalah cerita-cerita itu. Allah yang gambar, manusia yang pilih. Semua yang kita pilih adalah takdir Allah."),
        ("Makna taqdir", "Pandai menetapkan pilihan with argumentasi logis yang syar’i.", "Mukmin yang mempelajari Al-Quran akan tahu and paham bahwa Allah memberikan hak pilih kepada manusia. Atas dasar pertimbangan apa kita memilih? Jawabnya adalah with logika and syariat. Dua argumentasi ini tak boleh terlepas and terpisah. Contoh kalau dua argumentasi itu terlepas maka hasilnya adalah kesalahan atau bahkan dosa ; korupsi berjamaah secara logika pasti aman, sebab semua orang korupsi. Tapi walaupun begitu kalau kita melakukannya maka kita tetap dapat dosa."),
        ("Makna taqdir", "Memahami bahwa setiap pilihan ada resiko & konsekuensinya.", "Mukmin yang cerdas juga paham bahwa Allah memberikan banyak pilihan lengkap with risikonya masing-masing. Dilihat dari risiko, maka terdapat tiga situasi : Terkadang ada pilihan antara yang tidak berisiko sama sekali with yang beresiko. Ada juga antara yang risikonya besar with yang risikonya kecil. Tapi sesungguhnya lebih banyak pilihan yang keduanya punya risiko yang sama besarnya."),
        ("Makna taqdir", "Menerima kesalahan with wajar & tidak menyalahkan apapun and siapapun tanpa argumentasi yang logis and syar’i", "Mukmin yang dewasa and cerdas akan mengambil semua tanggung jawab terhadap apa yang dipilihnya sendiri apabila terdapat kesalahan atau kegagalan. Jangan seperti anak kecil yang selalu menolak untuk salah and selalu menyalahkan orang lain."),
        ("Makna ukhuwah", "Memahami konflik as ujian & alat untuk belajar.", "Arti sejati dari ukhuwah adalah ikatan persaudaraan atau persatuan yang dibangun atas dasar iman atau Akidah (QS. Al-Hujurat: 10). Secara sederhana kita bisa sebut persaudaraan muslim. Dan seperti semua kehidupan sosial, pasti terdapat konflik di tengah-tengah persaudaraan itu (baca ; keluarga). Namun konflik itu tidak boleh dipandang as keburukan, sebaliknya konflik harus dipandang as proses untuk menuju harmonis. Sesungguhnya pada konflik itu kita belajar untuk menuju harmonisasi."),
        ("Makna ukhuwah", "Memahami makna dari kata benar, baik, & indah.", "Ada tiga nilai yang harus dipahami with sempurna, yaitu ; Benar adalah menurut pandangan Allah Swt. Baik adalah menurut pandangan manusia. Sedangkan indah adalah gabungan dari benar and baik. Pemahaman ini sangat penting untuk menjaga ukhuwah tetap utuh. Terutama untuk ukhuwah insaniyah and wataniyah. Ukhuwah yang tertinggi adalah ukhuwah Akidah. Konflik-konfliknya sebetulnya simple, misalnya ; Kasus poligami banyak wanita muslim yang menolak menjalaninya. Dan itu tak apa. Asal wanita itu tetap mengakui bahwa hukum poligami itu benar dari Allah, and memang disyariatkan. Kasus perbedaan fiqhiyah, kasus perbedaan penafsiran Quran and hadith, dsb. Masalah-masalah ini ada tuntunannya, selama pelakunya cerdas maka mereka pasti menemukan jawabannya di dalam Islam. Tapi ada jenis ukhuwah lain yang jauh lebih rumit. Yaitu ukhuwah Insaniyah yaitu persaudaraan sesama manusia tanpa memandang agama. Dan ukhuwah Wataniyah yaitu persaudaraan sebangsa and setanah air. Pada dua jenis ukhuwah inilah konsep nilai benar baik and indah ini harus diterapkan with hati-hati. Masalah-masalah yang jauh lebih rumit and kompleks, seperti misalnya ; Apakah pemerintah muslim boleh melarang orang kristen untuk mendirikan gereja? Apakah boleh muslim boleh menjual khmar kepada orang-orang nonmuslim ? Apakah boleh wanita muslim menikah with pria nonmuslim ? Atau sebaliknya? Apakah boleh muslim bekerjasama mendirikan perusahaan bersama orang yahudi with menjalankan riba ? Apakah pemerintah boleh melarang muslim yang ingin menghidupkan system khilafah? Disinilah arti penting konsep tiga nilai tadi yaitu “Benar, baik, and indah”"),
        ("Makna ukhuwah", "Menyikapi konflik with ; “Tabayun. Muhasabah, & Ishlah”", "Tabayun adalah memastikan kebenaran informasi, konfirmasikan kepada pengucap asli, jangan berpegang kepada “Katanya” atau yang lebih buruk lagi “Asumsi”. Muhasabah adalah mencari kesalahan diri sendiri. Ishlah adalah berbaikan. Idealnya semua konflik harus diakhiri with berbaikan, kembali berhubungan with baik. Bukan saling mengalahkan and mematikan. Semua jenis konflik harus diselesaikan with tiga langkah diatas."),
        ("Makna ukhuwah", "Memahami bahwa perbedaan adalah kehendak Allah & akibat dari perspektif yang berbeda.", "Apa arti konflik ? konflik adalah pertentangan atau perselisihan antara individu maupun kelompok yang muncul karena perbedaan kepentingan, tujuan, nilai, atau pandangan. Siapakah yang menciptakan konflik? Manusia. Manusialah yang bertengkar, saling berselisih, saling ingin menang, and saling ingin mendominasi. Apakah Allah mengijinkan konflik itu terjadi? Jawabnya iya. Ada di QS. An-Nahl 93. Namun sebenarnya semua perbedaan itu tidak otomatis menciptakan konflik yang buruk. Semua perbedaan itu bisa disikapi with baik, baik, dewasa, and winwin solutions."),
        ("Makna ukhuwah", "Pandai menyikapi perbedaan with indah (benar & baik).", "Ini sudah dibahas with sangat jelas di ayat-ayat pondasi di tema ukhuwah (QCB). Yang pertama semua perbedaan dikembalikan kepada Quran and hadis. (QS An-Nisa' 59) Yang kedua, jika masih terjadi perbedaan, padahal masing-masing memiliki dalil (Quran & Hadits), maka urusannya diserahkan kepada Allah Swt kelak di Akhirat. (QS Asy-Syura 10).")
    ]

    # Data Mental (34)
    mental_data = [
        ("Niat", "Prinsip belajar", "Belajar itu adalah ibadah. Belajar itu untuk tahu and bisa. “Belajar itu ibadah”, harus dijalankan with jujur, kalau tidak dilakukan with benar maka tidak akan mendapatkan pahala. belajar itu persis seperti ibadah, apabila tidak dilakukan with benar maka manfaatnya tidak akan di dapat. “Belajar itu untuk tahu and bisa”. Belajar itu bukan hanya untuk tahu (teori) tapi harus bisa di praktekkan. Bukan cuma di pahami tapi harus diamalkan, atau dilakukan atau di implementasi. Indikator: 1. Niat Belajar as Ibadah: Menjadikan belajar as bentuk pengabdian kepada Allah, Memulai belajar with doa and niat yang lurus. 2. Kesadaran akan Tujuan Ilmu: Menjadikan belajar bukan sekadar formalitas, tetapi untuk memahami kebenaran, Menempatkan ilmu as jalan menuju kedekatan with Allah. 3. Orientasi “Tahu and Bisa”: Belajar bukan hanya untuk hafal, tetapi untuk memahami and mengamalkan, Menjadikan ilmu as bekal praktik nyata dalam kehidupan. 4. Konsistensi dalam Menuntut Ilmu: Tekun belajar meski menghadapi kesulitan, Tidak mudah menyerah ketika belum paham. 5. Integrasi Ilmu and Amal: Menghubungkan pengetahuan with tindakan nyata, Menjadikan ilmu as pedoman dalam akhlak and ibadah. 6. Sikap Rendah Hati: Tidak sombong with ilmu yang dimiliki, Menyadari bahwa ilmu adalah amanah, bukan sekadar prestasi. 7. Spiritualitas dalam Belajar: Menjadikan belajar as sarana mendekatkan diri kepada Allah, Meyakini bahwa ilmu yang bermanfaat adalah yang membawa keberkahan."),
        ("Niat", "Tahu prioritas dari Indah, Benar, and baik.", "Prioritas 1 adalah indah yaitu gabungan dari benar and baik. Prioritas 2 adalah ‘Benar’ yaitu menurut pandangan Allah Swt. Prioritas 3 adalah ‘Baik’ yaitu menurut pandangan manusia. Kamu bukan hanya harus melakukan/mengerjakan apa yang kamu sukai saja, tetapi kamu harus melakukan apa yang penting and bermanfaat untukmu (walaupun kamu tidak suka). Tidak semua syariat bisa dijalankan with sempurna, misalnya seperti poligami (QS An-Nisa 3). Banyak wanita tidak ridlo with poligami walaupun itu syariatnya Allah. Wanita yang mampu ridlo and mampu menjalani poligami berarti telah menyelaraskan antara kebenaran with kebaikan. Prioritas kaum muslimin adalah “Indah” yaitu menggabungkan benar with baik. Indikator: 1. Menjadikan Benar as Fondasi. 2. Menempatkan Baik as Wajah. 3. Menjadikan Indah as Harmoni. 4. Prioritas yang Seimbang. 5. Integrasi Spiritualitas & Sosialitas."),
        ("Niat", "Sumpah SI 1  “Bahagia menjadi hamba Allah & siap menghadapNya.”", "Ada dua kata penting disini, “Hamba” and “bahagia”. Ada manusia yang tidak ridlo menjadi hamba, dia merasa terpaksa atau dipaksa, ia tinggi hati seperti iblis, yang tak terima karena logika sesatnya bahwa manusia dibuat dari tanah and dia dari api. Berbeda with mukmin yang mempelajari Al-Quran, ia bahagia, rela, ridlo menjadi seorang hamba atau budaknya Allah. Karena memang itulah kenyataannya. Manusia tak bisa setara apalagi lebih mulia dari Tuhan. Karena kita ridlo and bahagia, maka kita jauh lebih siap menghadapNya. Indikator: 1. Kebahagiaan dalam Penghambaan. 2. Konsistensi Ibadah. 3. Orientasi Akhirat. 4. Kesiapan Menghadap Allah. 5. Syukur & Sabar. 6. Integritas dalam Hidup. 7. Keteladanan Spiritual."),
        ("Niat", "Sumpah SI 2 “Bahagia menjadi umat Muhammad Saw & merindukan perjumpaan dengannya.”", "Mencintai orang yang tak pernah kita lihat, itu masalah besar. Banyak manusia tak punya rasa apapun with nabi Muhammad Saw. ada yang lebih parah lagi, ia membenci Muhammad Saw. Berbeda with mukmin yang mempelajari Al-Quran, ia bahagia, bahkan bangga menjadi umatnya Nabi Muhammad Saw. Kita pecinta sejati, mengenal with baik Nabi Muhammad, sejarahnya, kisah hidupnya, hadits-haditsnya, tunduk and patuh kepadanya. Karena itulah kita siap and bahkan merindukannya. Indikator: 1. Cinta kepada Rasulullah. 2. Menghidupkan Sunnah. 3. Kerinduan Spiritual. 4. Keteladanan Akhlak. 5. Syukur & Kebanggaan. 6. Orientasi Akhirat. 7. Dakwah & Teladan."),
        ("Niat", "Sumpah SI 3  “Jatuh cinta pada kalam Allah & siap hidup berpandu padanya.”", "Al-Quran adalah kalam Allah, Al-Quran adalah jejak Allah paling nyata di dunia ini. Merupakan kesalahan serius kalau manusia buta tentang Al-Quran. Kita mencinta Al-Quran. Dan pecinta sejati itu mempelajari Quran, and benar-benar menjadikan Quran as petunjuk kehidupan. Bukan cinta namanya kalau hanya menjadikan Al-Quran as bacaan belaka, hafalan belaka. Tidak di pelajari, tidak direnungi, tidak dijadikan pedoman kehidupan. Indikator: 1. Kecintaan pada Al-Qur’an. 2. Kedekatan with Kalam Allah. 3. Pemahaman and Tadabbur. 4. Amal yang Berpandu Al-Qur’an. 5. Konsistensi dalam Hidup. 6. Spiritualitas yang Mendalam. 7. Kerinduan akan Pertemuan with Allah."),
        ("Niat", "Sumpah SI 4  “Ingin mulia di akhirat with menghafal alQuran.”", "Mukmin yang hebat, bukan cuma pembaca saja, mukmin yang hebat adalah penghafal Al-Quran. Sebab pemahaman and pengamalan al-Quran sangat bergantung with kekuatan hafalan. Seorang mukmin harus mencari referensi dari Al-Quran tentang apapun yang dihadapinya. Dan ini akan sulit sekali apabila ia tidak menghafalnya. Indikator: 1. Niat yang Lurus. 2. Konsistensi dalam Menghafal. 3. Kedekatan Spiritual. 4. Integrasi Ilmu & Amal. 5. Orientasi Akhirat. 6. Kerendahan Hati. 7. Dakwah & Teladan."),
        ("Niat", "Sumpah SI 4 “Ingin Mulia di dunia with teknologi bisnis & dakwah.”", "Mukmin yang hebat tidak gagap with kehidupan dunia. Dia tidak hanya ahli tentang masalah akhirat saja. Ia harus ahli juga terhadap urusan duniawi. Teknologi and bisnis adalah tanda / tren jaman ini. Maka menguasainya adalah syarat mutlak kita bisa mendapatkan kebahagian dunia. Indikator: 1. Visi Terpadu. 2. Pemanfaatan Teknologi untuk Kebaikan. 3. Bisnis yang Beretika & Syariah. 4. Dakwah yang Kreatif & Relevan. 5. Integrasi Dunia & Akhirat. 6. Kepemimpinan & Keteladanan. 7. Orientasi Maslahat."),
        ("Niat", "Berpikir Besar", "Apa yang kamu inginkan itulah yang kamu dapat. Berpikirlah yang besar maka kamu akan dapat yang besar. Bercita-citalah yang tinggi, kalaupun tidak tercapai puncaknya, kamu sudah tinggi mendakinya. Misalnya cita-citamu menjadi menteri bidang teknologi, segagal-gagalnya kamu minimal menjadi staf ahli kementrian teknologi, atau staf di departemen kementrian teknologi. Indikator: 1. Visi Jangka Panjang. 2. Berani Bermimpi Besar. 3. Orientasi Maslahat. 4. Ketekunan & Disiplin. 5. Berani Mengambil Risiko. 6. Integrasi Nilai Spiritual. 7. Kemampuan Menginspirasi."),
        ("Niat", "Tidak ada rasa malu kecuali", "Ketika terpikir mau berbuat dosa. Ketika sedang berbuat dosa. and Setelah melakukan dosa. Tidak boleh ada rasa malu kecuali dalam tiga hal. pertama, ketika terpikir akan berbuat dosa. kedua, ketika sedang berbuat dosa. and ketiga, setelah melakukan dosa. Selain ketiga itu kita tidak layak punya perasaan malu, misalnya seperti malu bertanya, malu bicara dihadapkan umum, malu tampil, malu memimpin, malu punya ambisi, malu membicarakan potensi diri, dsb. Indikator: 1. Hanya Malu Sebelum Berbuat Dosa. 2. Hanya Malu Saat Berbuat Dosa. 3. Hanya Malu Setelah Berbuat Dosa. 4. Kesadaran Spiritual. 5. Komitmen Perbaikan. 6. Tidak malu dalam hal-hal yang positif."),
        ("Niat", "Mental Inisiatif", "Adalah kemampuan untuk bertindak tanpa menunggu perintah atau dorongan dari orang lain. inisiatif bukan sekadar “bergerak duluan,” melainkan mental yang menunjukkan kepedulian, tanggung jawab, and keberanian. Orang yang inisiatifnya bagus : Performa pengembangan dirinya akan pesat. Kepercayaan dirinya akan sangat baik. Performa kompetensinya akan sangat pesat. Orang yang berinisiatif biasanya lebih cepat belajar and menemukan solusi baru. Sering mendapatkan peluang, with bertindak lebih dulu, kesempatan untuk berkembang atau meraih posisi lebih baik, dapat cepat tercapai. Indikator: 1. Proaktif. 2. Berani Memulai. 3. Tanggung Jawab. 4. Kreatif dalam Solusi. 5. Konsistensi & Ketekunan. 6. Kepekaan Sosial. 7. Integrasi Nilai Spiritual & Moral."),
        ("Niat", "Kreatif / Daya cipta Adalah kemampuan mencipta sesuatu.", "Kemampuan untuk mencari ide, kemampuan untuk menciptakan sesuatu yang baru, yang sebelumnya belum ada. Daya cipta ini bukan hanya untuk mengcreate produk, tetapi juga untuk mengatasi masalah. Kita yakin bahwa Allah menciptakan satu masalah with 1000 solusinya. Indikator: 1. Berpikir Out of the Box. 2. Kaya Imajinasi. 3. Fleksibilitas Mental. 4. Problem Solver. 5. Ekspresi Unik. 6. Rasa Ingin Tahu Tinggi. 7. Berani Berbeda."),
        ("Niat", "Inovatif / Daya rubah Adalah kemampuan memodifikasi sesuatu.", "Kemampuan untuk memodifikasi sesuatu yang sudah ada, baik menambahinya with elementary baru ataupun mengurangi elemen yang sudah ada, yang modifikasi itu dapat menambah manfaat dari barang itu. Indikator: 1. Peka terhadap Masalah & Peluang. 2. Berani Bereksperimen. 3. Menghasilkan Ide Orisinal. 4. Adaptif & Fleksibel. 5. Fokus pada Nilai Tambah. 6. Integrasi Ilmu & Kreativitas. 7. Inspiratif."),
        ("Niat", "Mandiri", "Kemampuan untuk hidup with matang, baik : Secara emosional, Perilaku, and Nilai. Kemandirian emosional artinya bisa lepas dari ketergantungan orangtua. Kemandirian perilaku artinya bisa membuat keputusan sendiri and menanggung konsekuensinya. Bisa menuntaskan pekerjaan sendiri and bisa bekerjasama with orang lain. Kemandirian nilai artinya tunduk and taat pada nilai-nilai agama. Indikator: 1. Kemandirian Emosional. 2. Kemandirian Perilaku. 3. Kemandirian Nilai. 4. Tanggung Jawab Pribadi. 5. Integritas & Konsistensi."),
        ("Niat", "Punya action plan", "Punya rencana kehidupan yang ditulis secara rinci, baik : Timeline, Stepline, maupun Minor rutin. Action Plan terdiri dari Timeline, yaitu cita-cita and rencana pertahapnya sesuai patokan usia yang diinginkan. Stepline yaitu perincian aktivitas yang harus dikerjakan untuk mencapai semua target di usia tertentu. Minor routin, Yaitu perincian aktivitas detail/kecil yang harus diistiqomahi untuk mencapai agenda mayor. Indikator: 1. Berorientasi pada Tujuan. 2. Timeline yang Realistis. 3. Tahapan (Stepline) yang Sistematis. 4. Langkah Mayor & Minor. 5. Disiplin & Konsistensi. 6. Evaluasi & Penyesuaian. 7. Integrasi Nilai & Spiritualitas."),
        ("Jihad", "Sumpah SI 6  “Sadar bahwa dunia adalah game yang besar.”", "Seorang mukmin yang jeli, ia akan melihat bahwa dunia ini mirip game. Di sebuah game. Pemain yang menang akan dapat hadiah, and pemain yang kalah akan mati. Bedanya kalau game biasa kalau kita kalah, maka resikonnya hanya pulsa data. Tapi kalau game bernama dunia ini, kalau kita kalah, maka kita akan dapat neraka. Indikator: 1. Kesadaran Hidup = Ujian. 2. Memahami Aturan Main. 3. Strategi & Perencanaan. 4. Mental Kompetitif yang Sehat. 5. Ketekunan & Kesabaran. 6. Orientasi Akhirat. 7. Rasa Syukur & Tawakal."),
        ("Jihad", "Sumpah SI 7  “Setiap pilihan ada konsekuensinya.”", "Hidup ini dipenuhi pilihan. Kita harus memilih. Dan apapun yang klita pilih pasti ada konsekuensinya. Bahkan makan enak saja kalau kebanyakan kita bisa diabetes. Ini bisa ke seluruh urusan, misalnya urusan politik. Kalau kita memilih golput, sejatinya itu sudah memilih, yaitu memenangkan salah satu calon and membuat kalah calon lainnya. Indikator: 1. Kesadaran Risiko. 2. Pertimbangan Matang. 3. Tanggung Jawab atas Konsekuensi. 4. Sikap Hati-hati. 5. Kesiapan Menerima kenyataan. 6. Integritas dalam Pilihan. 7. Evaluasi Berkelanjutan."),
        ("Jihad", "Daya juang", "Daya juang adalah : Kemampuan untuk terus berikhtiar, Tidak menyerah, Tidak putus asa. Pikiran yang besar atau cita-cita yang tinggi, cuma jadi hayalan belaka, apabila tidak disertai with daya juang yang tinggi. Daya juang adalah kemampuan untuk terus berikhtiar : Tak peduli berapa kali kegagalan menghampiri, terus berikhtiar kembali. Tidak peduli betapa sulitnya, tidak pernah menyerah. Tidak peduli berapa lama harus berjuang berapa banyak harus berkurban, terus berikhtiar and tidak pernah berputus asa. Indikator: 1. Keteguhan. 2. Konsistensi Usaha. 3. Optimisme dalam Kesulitan. 4. Kemampuan Bangkit. 5. Disiplin & Kerja Keras. 6. Spiritualitas as Sumber Kekuatan. 7. Orientasi Jangka Panjang."),
        ("Jihad", "Kompetitif (Daya saing)", "Adalah kemampuan untuk : Bersaing, Merespon with benar kemenangan, Merespons with benar kekalahan. Ambisi adalah hal yang baik, keinginan untuk menang sama sekali bukan hal yang buruk, itu bahkan adalah salah satu sifat dasar manusia. Manusia tanpa ambisi atau manusia yang ambisinya kecil, sama seperti mobil tanpa bahan bakar. Semangat berkompetisi adalah bahan bakar aktif untuk menyalakan semangat, untuk menyalakan jihad, untuk mempertahankan endurance, dsb. Namun tentu saja hanya dalam urusan kebaikan (fastabiqhul khoirot), bukan dalam hal keburukan apalagi dosa. Indikator: 1. Siap Bersaing. 2. Merespons Kemenangan with Benar. 3. Merespons Kekalahan with Benar. 4. Sportivitas. 5. Tangguh and tawadlu. 6. Orientasi Perbaikan Diri."),
        ("Jihad", "Monetitatif (Daya menguangkan)", "Kemampuan untuk menghasilkan uang dari suatu produk. Kita tidak boleh hanya jadi pengguna dari suatu produk, kita juga tidak boleh hanya menjadi pembuat dari suatu produk, kita harus juga menjadi orang yang mendapatkan uang dari produk tersebut. Inilah kemampuan monetisasi. Kemampuan menghasilkan uang dari karya atau skill ini pondasinya adalah literasi finansial. Kemampuan dasar finansial atau literasi finansial itu adalah ; memahami tentang istilah : Pemasukan, Pengeluaran, Tabungan, Investasi, Hutang, and Pencatatan keuangan. Indikator: 1. Nilai Jual Karya. 2. Kreativitas Produktif. 3. Mental Entrepreneurial. 4. Kemampuan Branding & Promosi. 5. Konsistensi Produksi. 6. Adaptasi terhadap Pasar. 7. Integrasi Nilai & Etika."),
        ("Jihad", "Cara belajar", "Belajar merupakan aktivitas yang paling penting : Belajar merupakan perintah Allah yang pertama. Kita harus belajar with 3 alat belajar and Kita harus belajar with 3 cara belajar. Tiga Cara belajar itu adalah : “Tanya atau ditanya”, “Menulis notes”, and “Murajaah”. Indikator: 1. Tanya atau Ditanya. 2. Menulis Notes (Mencatat, Merangkum, Merespon). 3. Murajaah (Mengulang). 4. Kesadaran Belajar = Ibadah. 5. Disiplin & Konsistensi. 6. Integrasi Ilmu & Amal."),
        ("Jihad", "Mulai dari enol", "Semua orang sukses : selalu mulai dari enol, tidak ada yang instant, and tanpa jerih payah. Semua mulai dari enol, maksudnya adalah kesuksesan selalu dirintis terlebih dahulu. tidak ada yang instant, semua mulai dari enol. seperti manusia dewasa, dulunya ia juga bayi belajar berjalan, berlari, dsb sampai ia dewasa. Semua orang kaya dulunya juga memulai dari enol, dulu miskin, kemudan ia berjuang berkurban menderita jatuh bangun, sampai akhirnya ia memperoleh kekayaan tersebut. Indikator: 1. Kesadaran Proses. 2. Kerendahan Hati. 3. Kesabaran & Ketekunan. 4. Mental Belajar. 5. Disiplin Bertahap. 6. Optimisme Jangka Panjang. 7. Integrasi Nilai Spiritual."),
        ("Jihad", "Mental belajar", "Mental belajar adalah semangat untuk terus belajar : dimanapun, kapanpun, and dalam keadaan apapun. Tidak semua pelajar adalah pembelajar. Orang yang duduk dibangku sekolah belum tentu belajar. Tetapi orang yang belajar, pasti adalah seorang pembelajar walaupun ia tidak berada di sekolah. Ia belajar diluar sekolah, di jalanan, di perpustakaan, kala ia bekerja, kala ia di tengah masyarakat. ia tetap akan belajar saat ia kaya saat ia miskin. Ia akan terus belajar saat ia semangat atau sedang malas. Ia akan belajar dimanapun, kapanpun, and dalam keadaan apapun. Indikator: 1. Dimanapun. 2. Kapanpun. 3. Dalam Keadaan Apapun. 4. Rasa Ingin Tahu Tinggi. 5. Adaptif & Fleksibel. 6. Konsistensi & Disiplin. 7. Integrasi Nilai Spiritual."),
        ("Jihad", "Kontrol potensi", "Manusia sukses adalah mereka : yang tahu potensi dirinya, bisa merawat potensinya, and memanfaatkan potensi itu untuk mencapai tujuannya. Pertama tentu ia harus menemukan potensinya. Ia tahu niat, minat, and bakatnya. Setelah itu ia harus berjuang keras untuk merawat potensinya itu with belajar sungguh-sungguh, memperbanyak latihan, mengasahnya agar semakin tajam. Kemudian ia mampu menggunakannya untuk mencapai tujuannya. Misalnya keinginan untuk kaya, terkenal, and punya pekerjaan. Indikator: 1. Kesadaran Diri. 2. Rasa Syukur & Percaya Diri. 3. Perawatan Potensi. 4. Pengembangan Berkelanjutan. 5. Menggunakan potensi with baik. 6. Integrasi Nilai & Tujuan Hidup. 7. Evaluasi & Adaptasi."),
        ("Jihad", "Tiga kekuatan internal", "Manusia sukses adalah mereka yang memiliki tiga kekuatan yang ada dalam dirinya yaitu : “Punya tujuan”, “Bisa berubah”, and “Bisa mempertahankan perubahan tersebut.” Punya cita-cita yang tinggi adalah wujud dari berpikir besar. Cita-citanya tidak boleh hanya satu, sebab Allah memberikan banyak potensi pada diri manusia. Bisa berubah artinya, ia mampu meningkatkan dirinya. Bisa mempertahankan perubahan misalnya, ketika di ponten sholatnya sudah tertib and khusuk, maka setelah di rumah kebiasaan itu tidak boleh hilang. Indikator: 1. Punya Tujuan. 2. Bisa Berubah. 3. Bisa Mempertahankan Perubahan. 4. Kesadaran Konsekuensi. 5. Integrasi Nilai Spiritual."),
        ("Sabar", "Sumpah SI 8  “Semua baik and menjadi alat belajar.”", "Mukmin sejati tak pernah menyalahkan orang lain atau keadaan atau alam atau Tuhan. Sebaliknya, mukmin sejati itu yang bersyukur tentang apapun yang terjadi. setiap musibah sebenarnya selalu ada hikmahnya. bahkan Imam Syafii pernah bersyukur with adanya neraka, sebab kata beliau, neraka membuatnya takut berbuat dosa. Misalnya kalau kita kecopetan itu artinya ; kita kurang sedekah, atau kita kurang berhati-hati. Maka bagi orang mukmin yang hebat, “Semua itu baik and menjadi alat belajar.” Indikator: 1. Mindset Positif. 2. Fleksibel. 3. Kemampuan Refleksi. 4. Rasa Syukur. 5. Orientasi Belajar Seumur Hidup. 6. Integrasi Nilai Spiritual. 7. Ketahanan Emosional."),
        ("Sabar", "Sumpah SI 9 “Aku bagian dari masyarakat.”", "Salah satu tujuan penciptaan adalah menjadi manusia yang bermanfaat, and tak mungkin kita bisa bermanfaat with menjauhi masyarakat. Dari mana kita bisa mendapatkan pahala? Tanpa berinteraksi with masyarakat? Itu yang pertama, yang kedua adalah apakah kita bisa hidup tanpa masyarakat? Tanpa berinteraksi with orang lain? Tanpa hidup berdampingan with mereka ? manusia dirancang as makhluk sosial, maka sudah menjadi kodratnya untuk hidup bersama. Indikator: 1. Rasa Memiliki. 2. Keterlibatan Sosial. 3. Tanggung Jawab Sosial. 4. Solidaritas & Empati. 5. Kemampuan Berkolaborasi. 6. Identitas Sosial Islami. 7. Orientasi Kontribusi."),
        ("Sabar", "Sumpah SI 10 “Aku sedang menulis kitabku sendiri.”", "Allah yang maha perkasa saja menciptakan lauhil mahfudz untuk mencatat semua peristiwa. Allah menciptakan Roqib and Atit as malaikat yang bertugas khusus untuk mencatat kehidupan kita, baik buruknya perbuatan kita, dosa and pahala yang kita lakukan. Maka mukmin yang serdas pasti meniru with membuat catatan hidupnya sendiri, boleh seperti diary, boleh with cara lainnya, bebas. Yang jelas kita harus mengawasi hidup kita with catatan itu. Indikator: 1. Kesadaran Diri. 2. Refleksi & Introspeksi. 3. Tanggung Jawab Spiritual. 4. Disiplin Mencatat Kehidupan. 5. Orientasi Perbaikan Diri. 6. Integrasi Ilmu & Amal. 7. Konsistensi & Kejujuran."),
        ("Sabar", "Empat suara di dalam diri", "Suara malaikat, Suara syaithan, Suara kita yang pro with malaikat, and suara kita yang pro syaithan. Di dalam diri kita terdapat empat suara. Suara pertama adalah suara malaikat, ia terletak di hati. Suara yang kedua adalah suara syaithan, ia bersarang di hawa nafsu/di otak bawah manusia. Suara ketiga adalah suara diri sendiri yang pro with malaikat akal and hati. Sedangkan suara keempat adalah suara diri kita sendiri yang pro with syaithan, hawa nafsu, and badan kita. Indikator: 1. Kesadaran Spiritual. 2. Kemampuan Membedakan Suara. 3. Kontrol Diri. 4. Kecenderungan pada Kebaikan. 5. Muhasabah (Introspeksi). 6. Integrasi with Nilai Agama. 7. Konsistensi dalam Latihan Jiwa."),
        ("Sabar", "Kontrol Diri", "Manusia yang sukses adalah mereka yang memiliki kemampuan untuk mengendalikan diri, menahan godaan atau distraction yang merusak fokus. Implementasinya sangat luas. Dari yang terkecil misalnya menolak teman yang ngajak ngobrol di kelas, tidak melayani candaan teman di masjid ketika sholat. Sampai urusan besar seperti cita-cita. Misalnya cita-cita kita as penghafal Quran, tapi hanya karena sulit and bosan kita mudah berpaling dari tujuan utama lalu merubah cita-cita menjadi hanya ingin jadi pedagang. Padahal ia bisa jadi keduanya, yaitu jadi pedagang yang hafal Quran, namun urutannya tetap. Menghafal dulu, baru dagang. Indikator: 1. Kontrol Emosi & Nafsu. 2. Fokus pada Tujuan. 3. Disiplin dalam Rutinitas. 4. Kemampuan Menunda Kepuasan. 5. Kesadaran terhadap Distraksi. 6. Integrasi Spiritualitas. 7. Konsistensi & Istiqamah."),
        ("Sabar", "Mental Antisipatif (Daya tangkal)", "Antispasi adalah daya menangkal masalah. Yaitu kemampuan meramalkan masalah dimasa depan, kemudian dibarengi with kemampuan merancang pencegahan, agar masalah itu tidak jadi muncul. Dan juga dibarengi with rancangan untuk menanganinya masalah itu seandainya masalah itu benar-benar muncul. Diimplementasikan ke semua urusan, dari yang sederhana misalnya sedia payung sebelum hujan, atau merancang evakuasi ketika terjadi tsunami. Indikator: 1. Kesadaran Situasi. 2. Perencanaan ke Depan. 3. Kesiapan Menghadapi Risiko. 4. Fleksibilitas & Adaptasi. 5. Proaktif. 6. Evaluasi Berkelanjutan. 7. Integrasi Nilai Spiritual."),
        ("Sabar", "Keseimbangan 4 waktu", "Untuk mempertahankan prestasi kita harus menyeimbangkan 4 waktu : Time to pray, Time to learn, Time to rest, and Time to play. Manusia butuh empat waktu and empat asupan, yaitu waktu untuk beribadah, waktu untuk belajar, waktu untuk bermain, and waktu untuk beristirahat. Apabila empat waktu ini tercukupi maka terbentuklah keseimbangan yang baik. Ketika kita beribadah kita tidak mengantuk, ketika kita belajar kita tidak bercanda, ketika jam tidur kita tidak scrol-scrol HP, di waktu tamasya kita malah sibuk bekerja. Indikator: 1. Time to Pray (Waktu untuk beribadah). 2. Time to Learn (Waktu untuk belajar). 3. Time to Rest (Waktu untuk istirahat). 4. Time to Play (Waktu untuk rekreasi/hiburan). 5. Kesadaran Prioritas. 6. Disiplin & Konsistensi. 7. Integrasi Nilai Spiritual."),
        ("Sabar", "Mental ITMI", "Mental ITMI adalah kemampuan untuk menepis mudorotnya teknologi and berfokus kepada manfaat teknologi. Islamic Technology Mindset Instalation (ITMI) berisi argumentasi logis and syar’i yang menyampaikan bahwa teknologi itu hanyalah alat. Baik atau buruknya teknologi sangat bergantung kepada sang pembawanya, sama seperti pisau, ditangan perampok ia menjadi alat kejahatan. Tapi ditangan koki ia jadi alat untuk memasak makanan enak. Muslim sejati adalah mereka yang mampu menepis mudorotnya teknologi, and mampu memanfaatkan teknologi untuk bisnis and dakwah. Indikator: 1. Kesadaran Nilai. 2. Selektif dalam Penggunaan. 3. Orientasi Maslahat. 4. Kontrol Diri. 5. Literasi Digital. 6. Kreativitas Positif. 7. Integrasi Nilai Spiritual."),
        ("Sabar", "Mental menghargai karya sendiri", "Kemampuan menghargai karya sendiri, mensyukuri pencapaian, bangga with jerih payah sendiri. Mental ini adalah faktor yang penting untuk menjadi manusia yang produktif. Apapun hasil dari ikhtiar yang maksimal harus disyukuri apapun bentuknya. mungkin tidak langsung bagus, tapi kalau kita terus memperbaikinya maka suatu saat pasti akan bagus. Justru kalau kita membenci karya sendiri, malu mengakui karya sendiri, perfeksionis di waktu yang salah, bisa berakibat membunuh produktivitas and semakin memperparah kepercayaan dirimu. Membenci karya sendiri, selain buruk, itu merupakan perbuatan dosa (kufur nikmat). Menghargai karya sendiri artinya ; bangga with hasil capaian, terus mengevaluasi, and terus menyempurnakannya. Indikator: 1. Rasa Syukur & Apresiasi. 2. Percaya Diri. 3. Tanggung Jawab terhadap Karya. 4. Konsistensi Berkarya. 5. Evaluasi & Perbaikan. 6. Integrasi Nilai Spiritual. 7. Orientasi Manfaat."),
        ("Sabar", "Konflik manajemen", "Mental yang baik dalam mencegah and menangani konflik adalah : Tabayun, Muhasabah, and Isilah. Konflik manajemen adalah kemampuan mencegah and menghadapi serta menangani konflik with baik. Pertama kita harus menghindari konflik, namun apabila memang harus, kita tidak takut berkonflik. Ini seperti prinsip perang kaum muslimin “kita tidak menginginkan perang, tapi tidak takut berperang kalau diperangi.” Yang kedua adalah kemampuan dalam menangani konflik. with tiga langkah, tabayun, muhasabah, and ishlah. Tabayun adalah memastikan kebenaran informasi, konfirmasikan kepada pengucap asli, jangan berpegang kepada “Katanya” atau yang lebih buruk lagi “Asumsi”. Muhasabah adalah mencari kesalahan diri sendiri, and Ishlah adalah berbaikan. Idealnya semua konflik harus diakhiri with berbaikan, kembali berhubungan with baik. Bukan saling mengalahkan and mematikan. Indikator: 1. Tabayun (Cek Kebenaran). 2. Muhasabah (Introspeksi). 3. Islah (Berbaikan). 4. Kedewasaan Emosi. 5. Orientasi Maslahat. 6. Integrasi Syariat.")
    ]

    # Data Soft Skill (14)
    softskill_data = [
        ("Kharisma", "Keinginan untuk selalu mengembangkan diri.", "Kharisma ini adalah karunia Allah Swt. Isya Allah akan diberikan kepada orang yang memperlakukan orang lain with indah, benar, atau baik. Untuk itu ia harus memiliki : Keinginan untuk selalu mengembangkan diri. Sikap and perbuatan orang lain itu ada tiga warna. Ada yang tidak menyenangkan, ada yang menyenangkan, and ada yang belum jelas. Agar mampu merespons with indah, seorang harus memiliki empat kecerdasan yang tinggi. Ketika seseorang memiliki dorongan untuk terus “mengembangkan diri” ia akan lebih terbuka, sabar, and bijak. Ia tidak hanya melihat tindakan orang lain as masalah, tetapi juga as kesempatan untuk mengasah ketajaman kognitif, emotional, and spiritualnya. With kesadaran seperti ini, tanggapan atau respon yang muncul bukan sekadar reaksi spontan, melainkan respons and tanggapan yang posisi and penuh makna."),
        ("Kharisma", "Kesetiaan pada Agama dalam wujud berbuat benar", "“Kesetiaan pada agama” adalah pondasi yang vital. Kesetiaan ini harus diwujudkan secara nyata dalam tindakan sehari-hari: berkata jujur, berlaku adil, penghormatan, egaliter, and nilai-nilai Islam lainnya. Islam akan memberikannya pedoman yang menuntun hati and pikirannya. With pedoman itu, ia mampu merespons sikap and perbuatan orang lain with indah ; tidak impulsif melainkan with ketenangan, kasih, and kebijaksanaan. Kesetiaan pada agama menjadikan setiap responsnya bukan sekadar jawaban biasa tetapi cerminan kebenaran Islam yang Mulia."),
        ("Kharisma", "Menyayangi manusia, dalam wujud memaafkan & memaklumi.", "Hampir semua konflik dipicu oleh respon yang buruk. Agar seseorang bisa memberikan tanggapan atau respons yang baik, ia perlu memiliki ‘Rasa kasih sayang” yang wujud nyatanya adalah “mudah memaklumi and mudah memaafkan.” Ketika seseorang terbiasa memaafkan and memaklumi, ia mampu melihat kelemahan orang lain as bagian dari kemanusiaan, bukan as serangan and alasan untuk marah. Dari rasa itu (Rasa kasih sayang) lahirlah tanggapan atau respon yang indah—tenang, penuh pengertian, and menyejukkan. Rasa itu (Rasa kasih sayang) menjadikan setiap interaksi with orang lain as kesempatan untuk menebar kebenaran and kebaikan."),
        ("Power", "Kesetiaan pada tujuan.", "Power ini adalah karunia Allah Swt. Isya Allah akan diberikan kepada orang yang memiliki : Kesetiaan pada tujuan. Power adalah kekuatan seseorang dalam menghadapi kendala yang merintangi terealisasinya tujuan. Ia berani menatap and menerjang rintangan. Ia akan mengerahkan tenaga and pikirannya, lalu melangkah maju tanpa gentar. Kekuatan seperti itu hanya lahir dari “kesetiaan pada tujuan.” Kesetiaan pada tujuan membuat seseorang tidak mudah goyah and mundur menghadapi sikap and perbuatan orang lain baik berupa hambatan atau godaan yang akan menghalanginya dari tujuan. Untuk orang yang setia pada tujuannya, rintangan-rintangan itu malah menjadi bahan bakar dari kekuatannya."),
        ("Power", "Kemauan untuk berkurban demi tercapainya tujuan.", "Kesetiaan pada tujuan, tidak mungkin tegak tanpa kesiapan and kesediaan untuk berkurban. Pengorbanan itu artinya “Rela melepas kenyamanan.\", “Rela menghabiskan waktu and tenaga.”, “Rela memberikan apapun yang kita miliki.” demi tercapainya tujuan. Semua orang yang kita temui dalam perjalanan menuju tujuan kita pasti meminta sesuatu dari kita, and kita tak punya pilihan lain selain memberikannya with benar. Atasan meminta kita bekerja keras, bawahan meminta integritas kita, partner meminta loyalitas kita, konsumen meminta layanan kita, dst. Semua itu adalah bentuk dari yang namanya “pengorbanan”."),
        ("Power", "Kekuatan untuk mengelola konflik.", "Konflik adalah bagian tak terpisahkan dari perjalanan menuju tujuan. Pasti ada konflik di semua perjalanan. Sebagian besar konflik pasti berhubungan with sikap and perbuatan orang lain, maka yang dimaksud with mengelola konflik adalah juga “Mengelola sikap and perbuatan orang lain”. Konflik harus dikelola with baik, kalau tidak ia hanya akan menguras energi kita. Waktu and tenaga habis dalam pertentangan perselisihan and pertengkar yang sebenarnya tidak perlu. With kekuatan and kepandaian dalam mengelola konflik (baca ; manusia), seseorang mampu menjaga fokus, menenangkan suasana, and mengubah perbedaan menjadi peluang untuk tercapainya tujuan."),
        ("Power", "Keberanian untuk mengambil keputusan and menanggung resikonya.", "Seperti semua perjalanan menuju suatu tujuan, pasti akan ada persimpangan jalan yang menghadirkan kebingungan kebimbangan. Di saat seperti inilah “Keputusan yang tepat mesti diambil.” Keputusan adalah titik penentu dalam perjalanan menuju tujuan. Tanpa keberanian mengambil keputusan, langkah akan terhenti di persimpangan. Dan pada setiap pilihan yang diambil pasti terdapat resikonya. Maka perlu kesanggupan untuk menanggung resikonya. Keputusan hanya akan menjadi kata-kata kosong tanpa kemampuan menanggung resiko. Menanggung risiko artinya menghadapi konsekuensi, siap belajar dari hasil, siap salah, and siap untuk terus bergerak."),
        ("Authority", "Memahami apa yang ia buat atau rencanakan (masterplan).", "Authority ini adalah kualitas yang akan tumbuh di dalam diri seseorang yang memiliki : Memahami apa yang ia buat atau rencanakan (masterplan). Authority adalah kemampuan untuk memberikan perintah with jelas and mudah dipahami, sehingga perintah itu dapat dilaksanakan with presisi. Agar seseorang benar-benar memiliki authority, ia harus memahami apa yang ia buat and ia rencanakan. Tanpa pemahaman terhadap apa yang ia buat and rencanakan, seseorang tidak mungkin bisa menciptakan kata perintah yang memiliki makna, arah and kekuatan yang jelas. Authority atau wewenang yang sejati bukan sekadar asal memerintah, melainkan juga memberikan tuntunan and petunjuk pelaksanaan with jelas sehingga perintah dapat dikerjakan with tepat."),
        ("Authority", "Pandai membujuk orang (Persuasif).", "Authority atau Wewenang bukan hanya soal memberi instruksi, tetapi juga bagaimana membuat orang lain mau melaksanakannya with penuh kesadaran. With kepandaian membujuk, perintah tidak terasa as beban atau paksaan, melainkan as ajakan sukarela yang masuk akal and menyenangkan untuk dikerjakan."),
        ("Authority", "Pandai memaksa orang (Imperatif).", "Terkadang kita berhadapan with orang yang tidak ingin mengerjakan perintah kita with alasan negatif maupun positif. Pada moment seperti inilah kita harus memastikan and memaksa orang agar menjalankan perintah kita, karena kita yakin bahwa perintah kita benar and harus dilaksanakan. Kemampuan memaksa (Imperatif) akan menjadi daya dorong yang efektif agar seseorang mengerjakan perintah walau ia tak menyetujui atau keberatan with perintah tersebut. Nanti ketika perintah itu benar-benar menghasilkan yang dikehendaki barulah orang yang kita perintah akan mengakui kelayakan otoritas kita."),
        ("Influential", "Kemampuan komunikasi dalam wujud interaksi & negoisasi.", "Influential adalah kualitas yang akan muncul apabila seseorang memiliki : Kemampuan komunikasi dalam wujud interaksi & negoisasi. Influential adalah kemampuan mempengaruhi orang lain with kata-kata yang jelas, kuat, and menarik, yang didukung oleh teladan yang selaras. Agar seseorang benar-benar memiliki kualitas ini, ia harus memiliki kemampuan komunikasi untuk berinteraksi atau bernegosiasi with orang lain, baik itu perorangan, kelompok, maupun massa. Komunikasi yang mumpuni membuat seseorang mampu menjalin kedekatan, membangun kepercayaan, and menyampaikan gagasan with meyakinkan. Influence bukan sekadar kemampuan mengeluarkan kata-kata, tetapi kekuatan sastra yang menggerakkan hati and pikiran orang lain untuk bertindak persis seperti yang kita inginkan."),
        ("Influential", "Kepandaian memilih diksi yang mumpuni.", "Komunikasi mestinya bukan sekedar kata-kata biasa, ia harus mengandung kekuatan keindahan and magnet yang bisa menggerakkan hati and pikiran orang yang mendengarnya. Kemampuan ini dibangun juga dari kepandaian memilih and mengolah diksi. Dari sinilah kualitas influence mulai tumbuh, and akan sukses apabila disusul with tauladan yang selaras."),
        ("Influential", "Daya ajak yang kuat.", "Kata-kata indah yang tidak dibarengi with daya ajak yang kuat mungkin hanya akan jadi pengetahuan and pemahaman. Tapi belum dapat menjadi penggerak. Daya ajak atau “Call To Action” membuat kata-kata tidak hanya terdengar baik benar and indah saja, tetapi juga mampu menggerakkan pikiran, hati and perbuatan orang lain."),
        ("Influential", "Tauladan yang selaras with pikiran and kata-katanya.", "Kata-kata yang indah akan kehilangan makna jika tidak sejalan with tindakan. Kata-kata ajakan juga akan gagal tanpa dibarengi with tauladan. Orang lain tidak hanya mendengar, tetapi juga melihat. Maka mereka tidak hanya mendengar kata-kata, tetapi mereka juga menuntut bukti.")
    ]

    for theme, name, desc in karakter_data:
        p = KMSParameter(category="karakter", theme=theme, name=name, description=desc)
        db.add(p)
    
    for theme, name, desc in mental_data:
        p = KMSParameter(category="mental", theme=theme, name=name, description=desc)
        db.add(p)
        
    for theme, name, desc in softskill_data:
        p = KMSParameter(category="softskill", theme=theme, name=name, description=desc)
        db.add(p)

    db.commit()
    print("Seeding KMS Parameters complete!")
    db.close()

if __name__ == "__main__":
    seed_parameters()
