import csv
import io

def parse_data(data_str, type_name):
    # Remove header if it exists
    lines = data_str.strip().split('\n')
    if lines[0].startswith('ID'):
        lines = lines[1:]
    
    f = io.StringIO('\n'.join(lines))
    reader = csv.reader(f)
    result = []
    for row in reader:
        if not row: continue
        # ID, TEMA, NAME, PENJELASAN
        theme = row[1].strip()
        name = row[2].strip()
        desc = row[3].strip()
        result.append((theme, name, desc))
    return result

softskill_str = """1,"Kharisma","Keinginan untuk selalu mengembangkan diri.","Kharisma ini adalah karunia Allah Swt. Isya Allah akan diberikan kepada orang yang memperlakukan orang lain dengan indah, benar, atau baik. Untuk itu ia harus memiliki : Keinginan untuk selalu mengembangkan diri. Sikap dan perbuatan orang lain itu ada tiga warna. Ada yang tidak menyenangkan, ada yang menyenangkan, dan ada yang belum jelas. Agar mampu merespons dengan indah, seorang harus memiliki empat kecerdasan yang tinggi. Ketika seseorang memiliki dorongan untuk terus “mengembangkan diri” ia akan lebih terbuka, sabar, dan bijak. Ia tidak hanya melihat tindakan orang lain sebagai masalah, tetapi juga sebagai kesempatan untuk mengasah ketajaman kognitif, emotional, dan spiritualnya. Dengan kesadaran seperti ini, tanggapan atau respon yang muncul bukan sekadar reaksi spontan, melainkan respons dan tanggapan yang posisi dan penuh makna."
2,"Kharisma","Kesetiaan pada Agama dalam wujud berbuat benar","“Kesetiaan pada agama” adalah pondasi yang vital. Kesetiaan ini harus diwujudkan secara nyata dalam tindakan sehari-hari: berkata jujur, berlaku adil, penghormatan, egaliter, dan nilai-nilai Islam lainnya. Islam akan memberikannya pedoman yang menuntun hati dan pikirannya. Dengan pedoman itu, ia mampu merespons sikap dan perbuatan orang lain dengan indah ; tidak impulsif melainkan dengan ketenangan, kasih, dan kebijaksanaan. Kesetiaan pada agama menjadikan setiap responsnya bukan sekadar jawaban biasa tetapi cerminan kebenaran Islam yang Mulia."
3,"Kharisma","Menyayangi manusia, dalam wujud memaafkan & memaklumi.","Hampir semua konflik dipicu oleh respon yang buruk. Agar seseorang bisa memberikan tanggapan atau respons yang baik, ia perlu memiliki ‘Rasa kasih sayang” yang wujud nyatanya adalah “mudah memaklumi dan mudah memaafkan.” Ketika seseorang terbiasa memaafkan dan memaklumi, ia mampu melihat kelemahan orang lain sebagai bagian dari kemanusiaan, bukan sebagai serangan dan alasan untuk marah. Dari rasa itu (Rasa kasih sayang) lahirlah tanggapan atau respon yang indah—tenang, penuh pengertian, dan menyejukkan. Rasa itu (Rasa kasih sayang) menjadikan setiap interaksi dengan orang lain sebagai kesempatan untuk menebar kebenaran dan kebaikan."
4,"Power","Kesetiaan pada tujuan.","Power ini adalah karunia Allah Swt. Isya Allah akan diberikan kepada orang yang memiliki : Kesetiaan pada tujuan. Power adalah kekuatan seseorang dalam menghadapi kendala yang merintangi terealisasinya tujuan. Ia berani menatap dan menerjang rintangan. Ia akan mengerahkan tenaga dan pikirannya, lalu melangkah maju tanpa gentar. Kekuatan seperti itu hanya lahir dari “kesetiaan pada tujuan.” Kesetiaan pada tujuan membuat seseorang tidak mudah goyah dan mundur menghadapi sikap dan perbuatan orang lain baik berupa hambatan atau godaan yang akan menghalanginya dari tujuan. Untuk orang yang setia pada tujuannya, rintangan-rintangan itu malah menjadi bahan bakar dari kekuatannya."
5,"Power","Kemauan untuk berkurban demi tercapainya tujuan.","Kesetiaan pada tujuan, tidak mungkin tegak tanpa kesiapan dan kesediaan untuk berkurban. Pengorbanan itu artinya “Rela melepas kenyamanan."", “Rela menghabiskan waktu dan tenaga.”, “Rela memberikan apapun yang kita miliki.” demi tercapainya tujuan. Semua orang yang kita temui dalam perjalanan menuju tujuan kita pasti meminta sesuatu dari kita, dan kita tak punya pilihan lain selain memberikannya dengan benar. Atasan meminta kita bekerja keras, bawahan meminta integritas kita, partner meminta loyalitas kita, konsumen meminta layanan kita, dst. Semua itu adalah bentuk dari yang namanya “pengorbanan”."
6,"Power","Kekuatan untuk mengelola konflik.","Konflik adalah bagian tak terpisahkan dari perjalanan menuju tujuan. Pasti ada konflik di semua perjalanan. Sebagian besar konflik pasti berhubungan dengan sikap dan perbuatan orang lain, maka yang dimaksud dengan mengelola konflik adalah juga “Mengelola sikap dan perbuatan orang lain”. Konflik harus dikelola dengan baik, kalau tidak ia hanya akan menguras energi kita. Waktu dan tenaga habis dalam pertentangan perselisihan dan pertengkaran yang sebenarnya tidak perlu. Dengan kekuatan dan kepandaian dalam mengelola konflik (baca ; manusia), seseorang mampu menjaga fokus, menenangkan suasana, dan mengubah perbedaan menjadi peluang untuk tercapainya tujuan."
7,"Power","Keberanian untuk mengambil keputusan dan menanggung resikonya.","Seperti semua perjalanan menuju suatu tujuan, pasti akan ada persimpangan jalan yang menghadirkan kebingungan kebimbangan. Di saat seperti inilah “Keputusan yang tepat mesti diambil.” Keputusan adalah titik penentu dalam perjalanan menuju tujuan. Tanpa keberanian mengambil keputusan, langkah akan terhenti di persimpangan. Dan pada setiap pilihan yang diambil pasti terdapat resikonya. Maka perlu kesanggupan untuk menanggung resikonya. Keputusan hanya akan menjadi kata-kata kosong tanpa kemampuan menanggung resiko. Menanggung risiko artinya menghadapi konsekuensi, siap belajar dari hasil, siap salah, dan siap untuk terus bergerak."
8,"Authority","Memahami apa yang ia buat atau rencanakan (masterplan).","Authority ini adalah kualitas yang akan tumbuh di dalam diri seseorang yang memiliki : Memahami apa yang ia buat atau rencanakan (masterplan). Authority adalah kemampuan untuk memberikan perintah dengan jelas dan mudah dipahami, sehingga perintah itu dapat dilaksanakan dengan presisi. Agar seseorang benar-benar memiliki authority, ia harus memahami apa yang ia buat dan ia rencanakan. Tanpa pemahaman terhadap apa yang ia buat dan rencanakan, seseorang tidak mungkin bisa menciptakan kata perintah yang memiliki makna, arah dan kekuatan yang jelas. Authority atau wewenang yang sejati bukan sekadar asal memerintah, melainkan juga memberikan tuntunan dan petunjuk pelaksanaan dengan jelas sehingga perintah dapat dikerjakan dengan tepat."
9,"Authority","Pandai membujuk orang (Persuasif).","Authority atau Wewenang bukan hanya soal memberi instruksi, tetapi juga bagaimana membuat orang lain mau melaksanakannya dengan penuh kesadaran. Dengan kepandaian membujuk, perintah tidak terasa sebagai beban atau paksaan, melainkan sebagai ajakan sukarela yang masuk akal dan menyenangkan untuk dikerjakan."
10,"Authority","Pandai memaksa orang (Imperatif).","Terkadang kita berhadapan dengan orang yang tidak ingin mengerjakan perintah kita dengan alasan negatif maupun positif. Pada moment seperti inilah kita harus memastikan dan memaksa orang agar menjalankan perintah kita, karena kita yakin bahwa perintah kita benar dan harus dilaksanakan. Kemampuan memaksa (Imperatif) akan menjadi daya dorong yang efektif agar seseorang mengerjakan perintah walau ia tak menyetujui atau keberatan dengan perintah tersebut. Nanti ketika perintah itu benar-benar menghasilkan yang dikehendaki barulah orang yang kita perintah akan mengakui kelayakan otoritas kita."
11,"Influential","Kemampuan komunikasi dalam wujud interaksi & negoisasi.","Influential adalah kualitas yang akan muncul apabila seseorang memiliki : Kemampuan komunikasi dalam wujud interaksi & negoisasi. Influential adalah kemampuan mempengaruhi orang lain dengan kata-kata yang jelas, kuat, dan menarik, yang didukung oleh teladan yang selaras. Agar seseorang benar-benar memiliki kualitas ini, ia harus memiliki kemampuan komunikasi untuk berinteraksi atau bernegosiasi dengan orang lain, baik itu perorangan, kelompok, maupun massa. Komunikasi yang mumpuni membuat seseorang mampu menjalin kedekatan, membangun kepercayaan, dan menyampaikan gagasan dengan meyakinkan. Influence bukan sekadar kemampuan mengeluarkan kata-kata, tetapi kekuatan sastra yang menggerakkan hati dan pikiran orang lain untuk bertindak persis seperti yang kita inginkan."
12,"Influential","Kepandaian memilih diksi yang mumpuni.","Komunikasi mestinya bukan sekedar kata-kata biasa, ia harus mengandung kekuatan keindahan dan magnet yang bisa menggerakkan hati dan pikiran orang yang mendengarnya. Kemampuan ini dibangun juga dari kepandaian memilih dan mengolah diksi. Dari sinilah kualitas influence mulai tumbuh, dan akan sukses apabila disusul dengan tauladan yang selaras."
13,"Influential","Daya ajak yang kuat.","Kata-kata indah yang tidak dibarengi dengan daya ajak yang kuat mungkin hanya akan jadi pengetahuan dan pemahaman. Tapi belum dapat menjadi penggerak. Daya ajak atau “Call To Action” membuat kata-kata tidak hanya terdengar baik benar dan indah saja, tetapi juga mampu menggerakkan pikiran, hati dan perbuatan orang lain."
14,"Influential","Tauladan yang selaras dengan pikiran dan kata-katanya.","Kata-kata yang indah akan kehilangan makna jika tidak sejalan dengan tindakan. Kata-kata ajakan juga akan gagal tanpa dibarengi dengan tauladan. Orang lain tidak hanya mendengar, tetapi juga melihat. Maka mereka tidak hanya mendengar kata-kata, tetapi mereka juga menuntut bukti." """

karakter_str = """1,"3 Tujuan Penciptaan Manusia","Memiliki tujuan hidup","Allah Swt tidak menciptakan manusia hanya untuk main-main, Allah menciptakan manusia dengan tujuan hadiah dan hukuman. Apabila tujuan itu dapat dicapai oleh manusia maka akan diganjar dengan hadiah surga. Apabila tujuan itu tidak tercapai, maka akan diganjar dengan neraka."
2,"3 Tujuan Penciptaan Manusia","Mampu memimpin & dipimpin","Tujuan penciptaan yang pertama adalah menjadi pemimpin (khalifah). Dan tak mungkin bisa menjadi pemimpin apabila tidak bisa dipimpin."
3,"3 Tujuan Penciptaan Manusia","Mampu mengatur diri & waktu dengan baik.","Tujuan penciptaan yang Allah canangkan tidak mungkin akan dapat dicapai oleh manusia apabila manusia itu tidak bisa mengatur diri dan waktunya dengan baik."
4,"3 Tujuan Penciptaan Manusia","Terlibat dalam kehidupan sosial & suka membantu","“Tujuan penciptaan manusia adalah ; agar manusia menjadi pemimpin, agar manusia menegakkan ibadah, agar manusia menjadi bermanfaat (terutama sebagai Ahlul Quran). Tujuan penciptaan yang ketiga ( agar manusia menjadi bermanfaat ) hanya mungkin diraih dengan cara terlibat dengan kehidupan sosial dan memberikan manfaat bagi orang lain dan masyarakat.”"
5,"3 Tujuan Penciptaan Manusia","Konsisten ibadahnya & memiliki hubungan yang kuat dengan Al-Quran","Apabila manusia tidak beribadah, maka jelas 1 tujuan penciptaan gagal ia raih. Apabila manusia tidak punya interaksi dengan Al-Quran (tidak bisa membaca, menghafal, memahami, mengamalkan, dan mengajarkannya) maka ia akan gagal mencapai 1 tujuan penciptaan yang Allah taala canangkan."
6,"3 Alat Belajar Manusia","Rasa ingin tahunya besar & gemar membaca","“Belajar” adalah perintah pertama yang turun melalui ayat QS Al-Alaq ayat 1-5. Ini membuktikan bahwa manusia hanya akan sukses apabila ia gemar membaca. Semakin banyak yang ia baca maka akan semakin kaya ia dengan pertanyaan-pertanyaan. Dan ciri manusia cerdas adalah “Banyak bertanya.” atau “Punya rasa ingin tahu yang besar.”"
7,"3 Alat Belajar Manusia","Berpikiran terbuka & suka mencoba hal baru.","Manusia yang menjalankan perintah Allah yang pertama. Akan Allah Swt jadikan ia bermindset yang growth dan open mind. Dengan begitu ia akan punya peluang besar untuk menjadi orang yang maksimal kecerdasan kognitifnya, emotionalnya, dan spiritualnya. Fisiknya sehat, mentalnya hebat, softskillnya indah, dan karakternya Quranik. Isya Allah bukan hanya pikiran dan perkataannya, tetapi juga perbuatannya."
8,"3 Alat Belajar Manusia","Imajinasinya kaya (Sumber K2IAM)","Awalnya semua manusia pandai menghayal, semestinya ini adalah pondasi dari kreativitas, inovasi, dan antisipatif. Namun sayang kebanyakan manusia membunuh kemampuan ini sejak dini. Bagaimana mereka membunuh potensi-potensi hebat ini ? Dengan menggunakan telinga mata dan hatinya untuk hiburan dan bermaksiat, bukan untuk membaca dan mempertajam rasa ingin tahunya."
9,"3 Alat Belajar Manusia","Berjuang memfilter 3 alat belajar.","Manusia yang banyak membaca, ia akan kaya dengan pengetahuan, kaya wawasannya, pikirannya besar, tinggi cita-citanya. Dan manusia yang seperti itu akan mudah memahami tentang Tuhan dan nilai-nilai agung agama. Dan manusia yang seperti itu akan semakin takut kepada Allah, dan akan semakin berhati-hati terhadap apa yang ia dengar, lihat, dan rasa."
10,"Sumber kejahatan","Menjadikan Islam sebagai identitas diri yang utama.","Sumber kejahatan manusia adalah hawa nafsu dan syaithan. Untuk menghadapi dua bahaya ini, manusia butuh nilai yang agung (Agama). Dan itulah fungsi yang utama dari agama, yaitu mengenalkan Tuhan dan mengenalkan tentang kebenaran, pahala, dan dosa. Maka keterikatan dengan agama merupakan syarat mutlak. Seharusnya manusia bangga dengan agama dan agama harusnya menjadi identitas dirinya. Misalnya “Kenalkan nama saya purwanto dan saya seorang muslim”. Manusia yang bahkan ‘malu’ dengan keislamannya, ia akan dekat dengan syaithan and ia akan gampang kalah dengan hawa nafsunya."
11,"Sumber kejahatan","Menjadikan Islam sebagai sumber kebenaran.","Agama Islam adalah patokan atau rujukan dari semua nilai. Termasuk nilai”Benar’ dan “Salah”. Manusia yang menjadikan agama sebagai sumber kebenaran, isya Allah tidak akan kebingungan. Berbeda dengan orang yang mengambil kebenaran dari selain agama, ia akan bingung dengan pertentangan yang banyak antara kebenaran yang pragmatis, bisa berbeda dengan kebenaran konsensus, atau bahkan mengambil pikiran manusia yang berbeda-beda standarnya, apalagi mengambil dari budaya manusia yang berbagai macam."
12,"Sumber kejahatan","Menjadikan Islam sebagai panduan dalam berpikir, berkata, & bertindak.","Seorang mukmin yang taat dan patuh kepada Islam tentu akan menjadikan Al-Quran sebagai petunjuk untuk berpikir berucap dan bertindak. Hidup seorang mukmin diatur sepenuhnya oleh Islam."
13,"Sumber kejahatan","Berusaha keras untuk berbuat benar.","“Manusia memang bukan malaikat yang pasti berbuat benar. Manusia Allah jadikan sebagai mahluk yang bebas memilih, ia digoda oleh syaithan dan hawa nafsunya. Oleh karena itulah, kadang manusia itu keliru, kadang salah, kadang bertentangan dengan agama.”Tetapi satu hal yang tak boleh hilang, yaitu keinginan untuk berbuat benar. Asalkan keinginan ini ada maka dosa dan kesalahan sangat mungkin akan Allah ampuni."
14,"Sumber kejahatan","Berusaha keras mencegah dirinya berbuat salah.","Manusia memang bukan malaikat yang pasti berbuat benar. Manusia Allah jadikan sebagai mahluk yang bebas memilih, ia punya hawa nafsu dan harus juga menghadapi godaan syaithan. Oleh karena itulah, kadang pilihan manusia itu keliru, kadang salah, kadang bertentangan dengan agama. Tetapi satu hal yang tak boleh hilang, yaitu keinginan untuk tidak berbuat salah. Asalkan keinginan ini ada maka manusia itu selalu diberi kesempatan oleh Allah untuk bertaubat."
15,"Sumber kejahatan","Memilih lingkungan & teman agar agama nya terjaga.","Salah satu cara agar manusia selalu ingin berbuat benar, dan selalu berusaha mencegah untuk berbuat salah… yaitu memilih lingkungan dan teman yang membuat agama dan moralnya terjaga."
16,"Akhirat prioritas","Menyadari bahwa dunia itu penting hanya karena itulah sat-satunya jalan menuju akhirat.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia sedang melakukan perjalanan yang panjang menuju dimensi akhirat. Dunia ini adalah halte, dan tempat dimana manusia mendapatkan tiket menuju ke surga. Oleh karena itu manusia tidak boleh tersesat dengan apapun yang ada di dunia, seperti harta, jabatan, kesenangan, dsb. Sebab itu adalah godaan dan ujian agar manusia melupakan akhirat dan surga."
17,"Akhirat prioritas","Cita-cita, visi, dan misinya dunia sekaligus akhirat.","Berdasarkan pemahaman tentang kesementaraan dunia, dan keabadian akhirat, maka seharusnya apapun yang dilakukan manusia, tujuannya bukan hanya untuk dunia ini. Tetapi harus juga bernilai ibadah. Maka mukmin yang memahami ini harus menjadikan cita-cita, visi, dan misinya itu bernilai dunia sekaligus bernilai akhirat."
18,"Akhirat prioritas","Menjadikan Allah, Quran dan Nabi Saw sebagai prioritas yang lebih besar dari semua urusan.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia sedang melakukan perjalanan yang panjang menuju dimensi akhirat. Dunia ini adalah halte, dan tempat dimana manusia mendapatkan tiket menuju ke surga. Tiket itu adalah ampunan Allah, cinta Allah dan ridlo nya Allah. Dan itu hanya akan didapat apabila mukmin menjadikan Al-Quran sebagai kitab petunjuk dan menjadikan Nabi Muhammad sebagai junjungan dan tauladan yang utama. Maka dalam segala urusan, manusia harus merujuk kepada Islam agar tidak bertentangan dengan Allah Swt, Kitabullah, dan Nabi Saw."
19,"Makna ujian","Memahami bahwa ujian adalah keniscayaan.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa dan tangis. Yang paling terasa menyakitkan adalah ujian berbentuk tangis. Ini yang sering ditolak oleh manusia. Padahal tak mungkin menolak ujian. Ujian adalah keniscayaan. Pasti terjadi."
20,"Makna ujian","Memahami bahwa bentuk ujian itu berupa tawa & tangis.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa dan tangis. Dua macam ujian ini sebenarnya membuat kita bisa bersabar dan tangguh. Jangan terlalui senang, sebab di depan ada neraka. Tapi juga jangan terlalu sedih, sebab di depan ada surga."
21,"Makna ujian","Memahami bahwa ujian berupa tangis harus dijawab dengan jihad dan sabar (terus berikhtiar).","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa dan tangis. Menghadapi ujian berupa keburukan seperti musibah, kehilangan, kecelakaan, didzolimi orang, dsb. Manusia harus berjihad, yaitu terus berikhtiar. Tidak boleh menyerah dan putus asa."
22,"Makna ujian","Memahami bahwa ujian berupa tawa harus dijawab dengan kendali diri, jangan sombong dan bermaksiat.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani ujian. Dan ujian itu bentuknya tawa dan tangis. Menghadapi ujian berupa kebaikan seperti fisik yang baik, rizqi melimpah, kemudahan, dsb. Manusia harus bersyukur dan bersabar, wujud nyata (dari syukur dan sabar) nya adalah tidak boleh sombong dan bermaksiat."
23,"Makna ujian","Memahami bahwa ujian itu adalah peluang untuk berkembang.","Apabila manusia jeli, maka akan jelaslah bahwa disetiap ujian terkandung peluang. Bayangkan ini seperti ujian sekolah yang kalau kita berhasil menyelesaikan dengan baik (nilainya tinggi) maka kita akan naik kelas. Dari SD menuju SMP, menuju SMA, menuju S1, S2, dan S3. Itulah hakikat ujian sebagai “Peluang untuk berkembang”."
24,"Makna ujian","Memiliki daya tahan yang baik terhadap tekanan, kesulitan, & stress.","Semua ujian menuntut fokus dan energi tambahan untuk menghadapinya. Manusia harus punya daya tahan terhadap tekanan, kesulitan, dan stress. Kalau tidak, ia akan kalah, menyerah, dan putus asa. Maka manusia harus berlatih dan membangun daya tahan yang baik, sama seperti dunia gym. Kita tidak bisa langsung angkat barbel 100 kg, kita harus melatih diri dr 1 kg, menuju 2 kg, 3kg, 4 kg, dst, dst. Dari satu ujian ke ujian yang lain hakikatnya adalah “kita sedang berlatih.”"
25,"Makna ujian","Mampu menemukan hikmah dibalik ujian (baik di awal, di tengah, maupun di akhir)","Apabila manusia jeli, maka akan jelaslah bahwa disetiap ujian terkandung hikmah. Bayangkan ini seperti ujian sekolah yang kita jalani. Di SD kita mendapatkan misalnya 10 ilmu, maka di SMP kita mendapat lebih banyak ilmu, di SMA semakin banyak, di universitas akan semakin banyak lagi, seperti itu terus-menerus. Maka ketika diuji jangan hanya fokus ke penderitaannya tapi fokus juga ke hikmah dan manfaat yang kita dapat dari ujian itu. Baik di awal ujian, atau di tengah ujian, atau di akhir ujian."
26,"Makna jihad","Setia dengan tujuan & yakin bahwa tujuan itu akan tercapai.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa manusia di dunia ini hakikatnya adalah sedang menjalani perjalanan menuju kesuksesan atau kegagalan. Baik kesuksesan dunia maupun kesuksesan akhirat. Kesuksesan akhirat itu adalah surga dan melihat wajah Allah Taala. Sedangkan kesuksesan dunia lebih banyak bentuknya, misalnya kaya, jabatan, popularitas, dsb. Salah satu rahasia kesuksesan itu adalah “Merasa yakin, bahwa kita akan mendapatkan kesuksesan itu.” Dan setia dengan tujuan itu."
27,"Makna jihad","Memiliki endurance (kekuatan menderita) yang baik.","Mukmin yang jeli akan mendapati sebuah kenyataan, bahwa di setiap ujian terdapat perjalanan. Ada yang pendek dan ada yang panjang. Untuk perjalanan pendek itu bagaikan lomba lari jarak pendek, triknya hanyalah “Berlari sekuat tenaga, sekencang-kencangnya..” Tapi untuk perjalanan yang panjang seperti marathon, kita harus menjaga tenaga, jangan sampai kehabisan ditengah perjalanan. Harus diatur dengan baik agar sampai ke garis finish. Inilah yang disebut dengan endurance, yaitu konsisten mengatur energi hingga di garis finish."
28,"Makna jihad","Lebih terobsesi pada proses (ikhtiar) daripada hasil.","Disetiap ujian ada yang namanya “hasil” dan ada yang namanya “proses”. Mukmin sejati harus waspada, sebab di dalam ujian hasil akan tertolak apabila prosesnya keliru. Contoh, kalau kita mencontek di waktu ujian maka apabila dipergoki maka kita langsung dianggap gagal. Maka jangan hanya terobsesi pada hasil, tapi juga harus terobsesi pada kesempurnaan proses, artinya prosesnya harus bersih dari dosa."
29,"Makna jihad","Menerima kegagalan dengan baik & pandai mengambil hikmah untuk ikhtiar berikutnya.","Disetiap ujian ada yang namanya berhasil ada yang namanya gagal. Di setiap tema ujian Allah mentaqdirkan beberapa kegagalan sebelum sampai pada kesuksesan. Maka jangan menyerah terhadap kegagalan, sebab setelah kegagalan itu pasti ada kesuksesan. Pelajari kegagalan itu, ambil hikmahnya, sebagai catatan untuk memperbaiki ikhtiar yang berikutnya."
30,"Makna taqdir","Menerima masa lalu sebagai taqdir Allah yang terbaik.","Mukmin yang mempelajari Al-Quran akan tahu dan paham tentang konsep takdir. Yaitu ketetapan yang Allah Al Khaliq gambarkan untuk manusia. Gambar ini berupa milyaran garis cerita untuk satu manusia, milyaran cerita itu walau variasi ceritanya bermilyar-milyar namun semua nya hanya dengan dua tujuan akhir, yaitu surga dan neraka. Maka jangan meratapi masa lalu dan jangan menyalahkan masa lalu, sebab apapun masa lalumu, itu adalah sebuah kebaikan menuju surgamu. Saya tidak menyalahkan orangtua saya yang miskin, saya tidak menyalahkan orangtua saya yang kafir, sebab justru itulah yang membuat saya kaya dan menemukan Islam. Saya menerima masa lalu saya sebagai masa lalu yang terbaik."
31,"Makna taqdir","Mengartikan masa depan sebagai tanggung jawab pribadi.","Mukmin yang baik dilarang menyalahkan masa lalu, dan mukmin yang baik harus mengartikan masa depan sebagai tanggung jawabnya pribadi. Percuma punya harta warisan yang banyak, sebab tanpa tanggung jawab dan ilmu harta warisan itu bisa habis. Percuma punya orangtua profesor, walaupun kita punya dna nya tapi tanpa didukung dengan kerja keras, kita akan tetap bodoh juga. Apapun yang akan terjadi masa depan itu adalah tanggung jawabmu pribadi."
32,"Makna taqdir","Memahami bahwa manusia diberi hak untuk memilih & semua pilihan itu adalah taqdir Allah.","Mukmin yang mempelajari Al-Quran akan tahu dan paham tentang konsep takdir. Yaitu ketetapan yang Allah Al Khaliq gambarkan untuk manusia. Gambar ini berupa milyaran garis cerita untuk satu manusia, milyaran cerita itu walau variasi ceritanya bermilyar-milyar namun semua nya hanya dengan dua tujuan akhir, yaitu surga dan neraka. Mukmin yang cerdas juga paham bahwa Allah memberikan hak pilih kepada manusia. Apa sebenarnya yang dipilih ? Jawabnya adalah cerita-cerita itu. Allah yang gambar, manusia yang pilih. Semua yang kita pilih adalah takdir Allah."
33,"Makna taqdir","Pandai menetapkan pilihan dengan argumentasi logis yang syar’i.","Mukmin yang mempelajari Al-Quran akan tahu dan paham bahwa Allah memberikan hak pilih kepada manusia. Atas dasar pertimbangan apa kita memilih? Jawabnya adalah dengan logika dan syariat. Dua argumentasi ini tak boleh terlepas dan terpisah. Contoh kalau dua argumentasi itu terlepas maka hasilnya adalah kesalahan atau bahkan dosa ; korupsi berjamaah secara logika pasti aman, sebab semua orang korupsi. Tapi walaupun begitu kalau kita melakukannya maka kita tetap dapat dosa."
34,"Makna taqdir","Memahami bahwa setiap pilihan ada resiko & konsekuensinya.","Mukmin yang cerdas juga paham bahwa Allah memberikan banyak pilihan lengkap dengan risikonya masing-masing. Dilihat dari risiko, maka terdapat tiga situasi : Terkadang ada pilihan antara yang tidak berisiko sama sekali dengan yang beresiko. Ada juga antara yang risikonya besar dengan yang risikonya kecil. Tapi sesungguhnya lebih banyak pilihan yang keduanya punya risiko yang sama besarnya."
35,"Makna taqdir","Menerima kesalahan dengan wajar & tidak menyalahkan apapun dan siapapun tanpa argumentasi yang logis dan syar’i","Mukmin yang dewasa dan cerdas akan mengambil semua tanggung jawab terhadap apa yang dipilihnya sendiri apabila terdapat kesalahan atau kegagalan. Jangan seperti anak kecil yang selalu menolak untuk salah dan selalu menyalahkan orang lain."
36,"Makna ukhuwah","Memahami konflik sebagai ujian & alat untuk belajar.","Arti sejati dari ukhuwah adalah ikatan persaudaraan atau persatuan yang dibangun atas dasar iman atau Akidah (QS. Al-Hujurat: 10). Secara sederhana kita bisa sebut persaudaraan muslim. Dan seperti semua kehidupan sosial, pasti terdapat konflik di tengah-tengah persaudaraan itu (baca ; keluarga). Namun konflik itu tidak boleh dipandang sebagai keburukan, sebaliknya konflik harus dipandang sebagai proses untuk menuju harmonis. Sesungguhnya pada konflik itu kita belajar untuk menuju harmonisasi."
37,"Makna ukhuwah","Memahami makna dari kata benar, baik, & indah.","Ada tiga nilai yang harus dipahami dengan sempurna, yaitu ; Benar adalah menurut pandangan Allah Swt. Baik adalah menurut pandangan manusia. Sedangkan indah adalah gabungan dari benar dan baik. Pemahaman ini sangat penting untuk menjaga ukhuwah tetap utuh. Terutama untuk ukhuwah insaniyah dan wataniyah. Ukhuwah yang tertinggi adalah ukhuwah Akidah. Konflik-konfliknya sebetulnya simple, misalnya ; Kasus poligami banyak wanita muslim yang menolak menjalaninya. Dan itu tak apa. Asal wanita itu tetap mengakui bahwa hukum poligami itu benar dari Allah, dan memang disyariatkan. Kasus perbedaan fiqhiyah, kasus perbedaan penafsiran Quran dan hadith, dsb. Masalah-masalah ini ada tuntunannya, selama pelakunya cerdas maka mereka pasti menemukan jawabannya di dalam Islam. Tapi ada jenis ukhuwah lain yang jauh lebih rumit. Yaitu ukhuwah Insaniyah yaitu persaudaraan sesama manusia tanpa memandang agama. Dan ukhuwah Wataniyah yaitu persaudaraan sebangsa dan setanah air. Pada dua jenis ukhuwah inilah konsep nilai benar baik dan indah ini harus diterapkan dengan hati-hati. Masalah-masalah yang jauh lebih rumit dan kompleks, seperti misalnya ; Apakah pemerintah muslim boleh melarang orang kristen untuk mendirikan gereja? Apakah boleh muslim boleh menjual khmar kepada orang-orang nonmuslim ? Apakah boleh wanita muslim menikah dengan pria nonmuslim ? Atau sebaliknya? Apakah boleh muslim bekerjasama mendirikan perusahaan bersama orang yahudi dengan menjalankan riba ? Apakah pemerintah boleh melarang muslim yang ingin menghidupkan system khilafah? Disinilah arti penting konsep tiga nilai tadi yaitu “Benar, baik, dan indah”"
38,"Makna ukhuwah","Menyikapi konflik dengan ; “Tabayun. Muhasabah, & Ishlah”","Tabayun adalah memastikan kebenaran informasi, konfirmasikan kepada pengucap asli, jangan berpegang kepada “Katanya” atau yang lebih buruk lagi “Asumsi”. Muhasabah adalah mencari kesalahan diri sendiri. Ishlah adalah berbaikan. Idealnya semua konflik harus diakhiri dengan berbaikan, kembali berhubungan dengan baik. Bukan saling mengalahkan dan mematikan. Semua jenis konflik harus diselesaikan dengan tiga langkah diatas."
39,"Makna ukhuwah","Memahami bahwa perbedaan adalah kehendak Allah & akibat dari perspektif yang berbeda.","Apa arti konflik ? konflik adalah pertentangan atau perselisihan antara individu maupun kelompok yang muncul karena perbedaan kepentingan, tujuan, nilai, atau pandangan. Siapakah yang menciptakan konflik? Manusia. Manusialah yang bertengkar, saling berselisih, saling ingin menang, dan saling ingin mendominasi. Apakah Allah mengijinkan konflik itu terjadi? Jawabnya iya. Ada di QS. An-Nahl 93. Namun sebenarnya semua perbedaan itu tidak otomatis menciptakan konflik yang buruk. Semua perbedaan itu bisa disikapi dengan baik, baik, dewasa, dan winwin solutions."
40,"Makna ukhuwah","Pandai menyikapi perbedaan dengan indah (benar & baik).","Ini sudah dibahas dengan sangat jelas di ayat-ayat pondasi di tema ukhuwah (QCB). Yang pertama semua perbedaan dikembalikan kepada Quran dan hadis. (QS An-Nisa' 59) Yang kedua, jika masih terjadi perbedaan, padahal masing-masing memiliki dalil (Quran & Hadits), maka urusannya diserahkan kepada Allah Swt kelak di Akhirat. (QS Asy-Syura 10)." """

mental_str = """1,"Niat","Prinsip belajar","Belajar itu adalah ibadah. Belajar itu untuk tahu dan bisa. “Belajar itu ibadah”, harus dijalankan dengan jujur, kalau tidak dilakukan dengan benar maka tidak akan mendapatkan pahala. belajar itu persis seperti ibadah, apabila tidak dilakukan dengan benar maka manfaatnya tidak akan di dapat. “Belajar itu untuk tahu dan bisa”. Belajar itu bukan hanya untuk tahu (teori) tapi harus bisa di praktekkan. Bukan cuma di pahami tapi harus diamalkan, atau dilakukan atau di implementasi. Indikator: 1. Niat Belajar sebagai Ibadah: Menjadikan belajar sebagai bentuk pengabdian kepada Allah, Memulai belajar dengan doa dan niat yang lurus. 2. Kesadaran akan Tujuan Ilmu: Menjadikan belajar bukan sekadar formalitas, tetapi untuk memahami kebenaran, Menempatkan ilmu sebagai jalan menuju kedekatan dengan Allah. 3. Orientasi “Tahu dan Bisa”: Belajar bukan hanya untuk hafal, tetapi untuk memahami dan mengamalkan, Menjadikan ilmu sebagai bekal praktik nyata dalam kehidupan. 4. Konsistensi dalam Menuntut Ilmu: Tekun belajar meski menghadapi kesulitan, Tidak mudah menyerah ketika belum paham. 5. Integrasi Ilmu dan Amal: Menghubungkan pengetahuan dengan tindakan nyata, Menjadikan ilmu sebagai pedoman dalam akhlak dan ibadah. 6. Sikap Rendah Hati: Tidak sombong dengan ilmu yang dimiliki, Menyadari bahwa ilmu adalah amanah, bukan sekadar prestasi. 7. Spiritualitas dalam Belajar: Menjadikan belajar sebagai sarana mendekatkan diri kepada Allah, Meyakini bahwa ilmu yang bermanfaat adalah yang membawa keberkahan."
2,"Niat","Tahu prioritas dari Indah, Benar, dan baik.","Prioritas 1 adalah indah yaitu gabungan dari benar dan baik. Prioritas 2 adalah ‘Benar’ yaitu menurut pandangan Allah Swt. Prioritas 3 adalah ‘Baik’ yaitu menurut pandangan manusia. Kamu bukan hanya harus melakukan/mengerjakan apa yang kamu sukai saja, tetapi kamu harus melakukan what penting dan bermanfaat untukmu (walaupun kamu tidak suka). Tidak semua syariat bisa dijalankan dengan sempurna, misalnya seperti poligami (QS An-Nisa 3). Banyak wanita tidak ridlo dengan poligami walaupun itu syariatnya Allah. Wanita yang mampu ridlo dan mampu menjalani poligami berarti telah menyelaraskan antara kebenaran dengan kebaikan. Prioritas kaum muslimin adalah “Indah” yaitu menggabungkan benar dengan baik. Indikator: 1. Menjadikan Benar sebagai Fondasi. 2. Menempatkan Baik sebagai Wajah. 3. Menjadikan Indah sebagai Harmoni. 4. Prioritas yang Seimbang. 5. Integrasi Spiritualitas & Sosialitas."
3,"Niat","Sumpah SI 1  “Bahagia menjadi hamba Allah & siap menghadapNya.”","Ada dua kata penting disini, “Hamba” dan “bahagia”. Ada manusia yang tidak ridlo menjadi hamba, dia merasa terpaksa atau dipaksa, dia tinggi hati seperti iblis, yang tak terima karena logika sesatnya bahwa manusia dibuat dari tanah dan dia dari api. Berbeda dengan mukmin yang memahami Al-Quran, ia bahagia, rela, ridlo menjadi seorang hamba atau budaknya Allah. Karena memang itulah kenyataannya. Manusia tak bisa setara apalagi lebih mulia dari Tuhan. Karena kita ridlo dan bahagia, maka kita jauh lebih siap menghadapNya. Indikator: 1. Kebahagiaan dalam Penghambaan. 2. Konsistensi Ibadah. 3. Orientasi Akhirat. 4. Kesiapan Menghadap Allah. 5. Syukur & Sabar. 6. Integritas dalam Hidup. 7. Keteladanan Spiritual."
4,"Niat","Sumpah SI 2 “Bahagia menjadi umat Muhammad Saw & merindukan perjumpaan dengannya.”","Mencintai orang yang tak pernah kita lihat, itu masalah besar. Banyak manusia tak punya rasa apapun dengan nabi Muhammad Saw. ada yang lebih parah lagi, ia membenci Muhammad Saw. Berbeda dengan mukmin yang memahami Al-Quran, ia bahagia, bahkan bangga menjadi umatnya Nabi Muhammad Saw. Kita pecinta sejati, mengenal dengan baik Nabi Muhammad, sejarahnya, kisah hidupnya, hadits-haditsnya, tunduk dan patuh kepadanya. Karena itulah kita siap dan bahkan merindukannya. Indikator: 1. Cinta kepada Rasulullah. 2. Menghidupkan Sunnah. 3. Kerinduan Spiritual. 4. Keteladanan Akhlak. 5. Syukur & Kebanggaan. 6. Orientasi Akhirat. 7. Dakwah & Teladan."
5,"Niat","Sumpah SI 3  “Jatuh cinta pada kalam Allah & siap hidup berpandu padanya.”","Al-Quran adalah kalam Allah, Al-Quran adalah jejak Allah paling nyata di dunia ini. Merupakan kesalahan serius kalau manusia buta tentang Al-Quran. Kita mencinta Al-Quran. Dan pecinta sejati itu mempelajari Quran, dan benar-benar menjadikan Quran sebagai petunjuk kehidupan. Bukan cinta namanya kalau hanya menjadikan Al-Quran sebagai bacaan belaka, hafalan belaka. Tidak di pelajari, tidak direnungi, tidak dijadikan pedoman kehidupan. Indikator: 1. Kecintaan pada Al-Qur’an. 2. Kedekatan dengan Kalam Allah. 3. Pemahaman dan Tadabbur. 4. Amal yang Berpandu Al-Qur’an. 5. Konsistensi dalam Hidup. 6. Spiritualitas yang Mendalam. 7. Kerinduan akan Pertemuan dengan Allah."
6,"Niat","Sumpah SI 4  “Ingin mulia di akhirat dengan menghafal alQuran.”","Mukmin yang hebat, bukan cuma pembaca saja, mukmin yang hebat adalah penghafal Al-Quran. Sebab pemahaman dan pengamalan al-Quran sangat bergantung dengan kekuatan hafalan. Seorang mukmin harus mencari referensi dari Al-Quran tentang apapun yang dihadapinya. Dan ini akan sulit sekali apabila ia tidak menghafalnya. Indikator: 1. Niat yang Lurus. 2. Konsistensi dalam Menghafal. 3. Kedekatan Spiritual. 4. Integrasi Ilmu & Amal. 5. Orientasi Akhirat. 6. Kerendahan Hati. 7. Dakwah & Teladan."
7,"Niat","Sumpah SI 4 “Ingin Mulia di dunia dengan teknologi bisnis & dakwah.”","Mukmin yang hebat tidak gagap dengan kehidupan dunia. Dia tidak hanya ahli tentang masalah akhirat saja. Ia harus ahli juga terhadap urusan duniawi. Teknologi dan bisnis adalah tanda / tren jaman ini. Maka menguasainya adalah syarat mutlak kita bisa mendapatkan kebahagian dunia. Indikator: 1. Visi Terpadu. 2. Pemanfaatan Teknologi untuk Kebaikan. 3. Bisnis yang Beretika & Syariah. 4. Dakwah yang Kreatif & Relevan. 5. Integrasi Dunia & Akhirat. 6. Kepemimpinan & Keteladanan. 7. Orientasi Maslahat."
8,"Niat","Berpikir Besar","Apa yang kamu inginkan itulah yang kamu dapat. Berpikirlah yang besar maka kamu akan dapat yang besar. Bercita-citalah yang tinggi, kalaupun tidak tercapai puncaknya, kamu sudah tinggi mendakinya. Misalnya cita-citamu menjadi menteri bidang teknologi, segagal-gagalnya kamu minimal menjadi staf ahli kementrian teknologi, atau staf di departemen kementrian teknologi. Indikator: 1. Visi Jangka Panjang. 2. Berani Bermimpi Besar. 3. Orientasi Maslahat. 4. Ketekunan & Disiplin. 5. Berani Mengambil Risiko. 6. Integrasi Nilai Spiritual. 7. Kemampuan Menginspirasi."
9,"Niat","Tidak ada rasa malu kecuali","Ketika terpikir mau berbuat dosa. Ketika sedang berbuat dosa. dan Setelah melakukan dosa. Tidak boleh ada rasa malu kecuali dalam tiga hal. pertama, ketika terpikir akan berbuat dosa. kedua, ketika sedang berbuat dosa. dan ketiga, setelah melakukan dosa. Selain ketiga itu kita tidak layak punya perasaan malu, misalnya seperti malu bertanya, malu bicara dihadapkan umum, malu tampil, malu memimpin, malu punya ambisi, malu membicarakan potensi diri, dsb. Indikator: 1. Hanya Malu Sebelum Berbuat Dosa. 2. Hanya Malu Saat Berbuat Dosa. 3. Hanya Malu Setelah Berbuat Dosa. 4. Kesadaran Spiritual. 5. Komitmen Perbaikan. 6. Tidak malu dalam hal-hal yang positif."
10,"Niat","Mental Inisiatif","Adalah kemampuan untuk bertindak tanpa menunggu perintah atau dorongan dari orang lain. inisiatif bukan sekadar “bergerak duluan,” melainkan mental yang menunjukkan kepedulian, tanggung jawab, dan keberanian. Orang yang inisiatifnya bagus : Performa pengembangan dirinya akan pesat. Kepercayaan dirinya akan sangat baik. Performa kompetensinya akan sangat pesat. Orang yang berinisiatif biasanya lebih cepat belajar dan menemukan solusi baru. Sering mendapatkan peluang, dengan bertindak lebih dulu, kesempatan untuk berkembang atau meraih posisi lebih baik, dapat cepat tercapai. Indikator: 1. Proaktif. 2. Berani Memulai. 3. Tanggung Jawab. 4. Kreatif dalam Solusi. 5. Konsistensi & Ketekunan. 6. Kepekaan Sosial. 7. Integrasi Nilai Spiritual & Moral."
11,"Niat","Kreatif / Daya cipta Adalah kemampuan mencipta sesuatu.","Kemampuan untuk mencari ide, kemampuan untuk menciptakan sesuatu yang baru, yang sebelumnya belum ada. Daya cipta ini bukan hanya untuk mengcreate produk, tetapi juga untuk mengatasi masalah. Kita yakin bahwa Allah menciptakan satu masalah dengan 1000 solusinya. Indikator: 1. Berpikir Out of the Box. 2. Kaya Imajinasi. 3. Fleksibilitas Mental. 4. Problem Solver. 5. Ekspresi Unik. 6. Rasa Ingin Tahu Tinggi. 7. Berani Berbeda."
12,"Niat","Inovatif / Daya rubah Adalah kemampuan memodifikasi sesuatu.","Kemampuan untuk memodifikasi sesuatu yang sudah ada, baik menambahinya dengan elementary baru ataupun mengurangi elemen yang sudah ada, yang modifikasi itu dapat menambah manfaat dari barang itu. Indikator: 1. Peka terhadap Masalah & Peluang. 2. Berani Bereksperimen. 3. Menghasilkan Ide Orisinal. 4. Adaptif & Fleksibel. 5. Fokus pada Nilai Tambah. 6. Integrasi Ilmu & Kreativitas. 7. Inspiratif."
13,"Niat","Mandiri","Kemampuan untuk hidup dengan matang, baik : Secara emosional, Perilaku, dan Nilai. Kemandirian emosional artinya bisa lepas dari ketergantungan orangtua. Kemandirian perilaku artinya bisa membuat keputusan sendiri dan menanggung konsekuensinya. Bisa menuntaskan pekerjaan sendiri dan bisa bekerjasama dengan orang lain. Kemandirian nilai artinya tunduk dan taat pada nilai-nilai agama. Indikator: 1. Kemandirian Emosional. 2. Kemandirian Perilaku. 3. Kemandirian Nilai. 4. Tanggung Jawab Pribadi. 5. Integritas & Konsistensi."
14,"Niat","Punya action plan","Punya rencana kehidupan yang ditulis secara rinci, baik : Timeline, Stepline, maupun Minor rutin. Action Plan terdiri dari Timeline, yaitu cita-cita dan rencana pertahapnya sesuai patokan usia yang diinginkan. Stepline yaitu perincian aktivitas yang harus dikerjakan untuk mencapai semua target di usia tertentu. Minor routin, Yaitu perincian aktivitas detail/kecil yang harus diistiqomahi untuk mencapai agenda mayor. Indikator: 1. Berorientasi pada Tujuan. 2. Timeline yang Realistis. 3. Tahapan (Stepline) yang Sistematis. 4. Langkah Mayor & Minor. 5. Disiplin & Konsistensi. 6. Evaluasi & Penyesuaian. 7. Integrasi Nilai & Spiritualitas."
15,"Jihad","Sumpah SI 6  “Sadar bahwa dunia adalah game yang besar.”","Seorang mukmin yang jeli, ia akan melihat bahwa dunia ini mirip game. Di sebuah game. Pemain yang menang akan dapat hadiah, dan pemain yang kalah akan mati. Bedanya kalau game biasa kalau kita kalah, maka resikonnya hanya pulsa data. Tapi kalau game bernama dunia ini, kalau kita kalah, maka kita akan dapat neraka. Indikator: 1. Kesadaran Hidup = Ujian. 2. Memahami Aturan Main. 3. Strategi & Perencanaan. 4. Mental Kompetitif yang Sehat. 5. Ketekunan & Kesabaran. 6. Orientasi Akhirat. 7. Rasa Syukur & Tawakal."
16,"Jihad","Sumpah SI 7  “Setiap pilihan ada konsekuensinya.”","Hidup ini dipenuhi pilihan. Kita harus memilih. Dan apapun yang klita pilih pasti ada konsekuensinya. Bahkan makan enak saja kalau kebanyakan kita bisa diabetes. Ini bisa ke seluruh urusan, misalnya urusan politik. Kalau kita memilih golput, sejatinya itu sudah memilih, yaitu memenangkan salah satu calon dan membuat kalah calon lainnya. Indikator: 1. Kesadaran Risiko. 2. Pertimbangan Matang. 3. Tanggung Jawab atas Konsekuensi. 4. Sikap Hati-hati. 5. Kesiapan Menerima kenyataan. 6. Integritas dalam Pilihan. 7. Evaluasi Berkelanjutan."
17,"Jihad","Daya juang","Daya juang adalah : Kemampuan untuk terus berikhtiar, Tidak menyerah, Tidak putus asa. Pikiran yang besar atau cita-cita yang tinggi, cuma jadi hayalan belaka, apabila tidak disertai dengan daya juang yang tinggi. Daya juang adalah kemampuan untuk terus berikhtiar : Tak peduli berapa kali kegagalan menghampiri, terus berikhtiar kembali. Tidak peduli betapa sulitnya, tidak pernah menyerah. Tidak peduli berapa lama harus berjuang berapa banyak harus berkurban, terus berikhtiar dan tidak pernah berputus asa. Indikator: 1. Keteguhan. 2. Konsistensi Usaha. 3. Optimisme dalam Kesulitan. 4. Kemampuan Bangkit. 5. Disiplin & Kerja Keras. 6. Spiritualitas sebagai Sumber Kekuatan. 7. Orientasi Jangka Panjang."
18,"Jihad","Kompetitif (Daya saing)","Adalah kemampuan untuk : Bersaing, Merespon dengan benar kemenangan, Merespons dengan benar kekalahan. Ambisi adalah hal yang baik, keinginan untuk menang sama sekali bukan hal yang buruk, itu bahkan adalah salah satu sifat dasar manusia. Manusia tanpa ambisi atau manusia yang ambisinya kecil, sama seperti mobil tanpa bahan bakar. Semangat berkompetisi adalah bahan bakar aktif untuk menyalakan semangat, untuk menyalakan jihad, untuk mempertahankan endurance, dsb. Namun tentu saja hanya dalam urusan kebaikan (fastabiqhul khoirot), bukan dalam hal keburukan apalagi dosa. Indikator: 1. Siap Bersaing. 2. Merespons Kemenangan dengan Benar. 3. Merespons Kekalahan dengan Benar. 4. Sportivitas. 5. Tangguh dan tawadlu. 6. Orientasi Perbaikan Diri."
19,"Jihad","Monetitatif (Daya menguangkan)","Kemampuan untuk menghasilkan uang dari suatu produk. Kita tidak boleh hanya jadi pengguna dari suatu produk, kita juga tidak boleh hanya menjadi pembuat dari suatu produk, kita harus juga menjadi orang yang mendapatkan uang dari produk tersebut. Inilah kemampuan monetisasi. Kemampuan menghasilkan uang dari karya atau skill ini pondasinya adalah literasi finansial. Kemampuan dasar finansial atau literasi finansial itu adalah ; memahami tentang istilah : Pemasukan, Pengeluaran, Tabungan, Investasi, Hutang, dan Pencatatan keuangan. Indikator: 1. Nilai Jual Karya. 2. Kreativitas Produktif. 3. Mental Entrepreneurial. 4. Kemampuan Branding & Promosi. 5. Konsistensi Produksi. 6. Adaptasi terhadap Pasar. 7. Integrasi Nilai & Etika."
20,"Jihad","Cara belajar","Belajar merupakan aktivitas yang paling penting : Belajar merupakan perintah Allah yang pertama. Kita harus belajar dengan 3 alat belajar dan Kita harus belajar dengan 3 cara belajar. Tiga Cara belajar itu adalah : “Tanya atau ditanya”, “Menulis notes”, dan “Murajaah”. Indikator: 1. Tanya atau Ditanya. 2. Menulis Notes (Mencatat, Merangkum, Merespon). 3. Murajaah (Mengulang). 4. Kesadaran Belajar = Ibadah. 5. Disiplin & Konsistensi. 6. Integrasi Ilmu & Amal."
21,"Jihad","Mulai dari enol","Semua orang sukses : selalu mulai dari enol, tidak ada yang instant, dan tanpa jerih payah. Semua mulai dari enol, maksudnya adalah kesuksesan selalu dirintis terlebih dahulu. tidak ada yang instant, semua mulai dari enol. seperti manusia dewasa, dulunya ia juga bayi belajar berjalan, berlari, dsb sampai ia dewasa. Semua orang kaya dulunya juga memulai dari enol, dulu miskin, kemudan ia berjuang berkurban menderita jatuh bangun, sampai akhirnya ia memperoleh kekayaan tersebut. Indikator: 1. Kesadaran Proses. 2. Kerendahan Hati. 3. Kesabaran & Ketekunan. 4. Mental Belajar. 5. Disiplin Bertahap. 6. Optimisme Jangka Panjang. 7. Integrasi Nilai Spiritual."
22,"Jihad","Mental belajar","Mental belajar adalah semangat untuk terus belajar : dimanapun, kapanpun, dan dalam keadaan apapun. Tidak semua pelajar adalah pembelajar. Orang yang duduk dibangku sekolah belum tentu belajar. Tetapi orang yang belajar, pasti adalah seorang pembelajar walaupun ia tidak berada di sekolah. Ia belajar diluar sekolah, di jalanan, di perpustakaan, kala ia bekerja, kala ia di tengah masyarakat. ia tetap akan belajar saat ia kaya saat ia miskin. Ia akan terus belajar saat ia semangat atau sedang malas. Ia akan belajar dimanapun, kapanpun, dan dalam keadaan apapun. Indikator: 1. Dimanapun. 2. Kapanpun. 3. Dalam Keadaan Apapun. 4. Rasa Ingin Tahu Tinggi. 5. Adaptif & Fleksibel. 6. Konsistensi & Disiplin. 7. Integrasi Nilai Spiritual."
23,"Jihad","Kontrol potensi","Manusia sukses adalah mereka : yang tahu potensi dirinya, bisa merawat potensinya, dan memanfaatkan potensi itu untuk mencapai tujuannya. Pertama tentu ia harus menemukan potensinya. Ia tahu niat, minat, dan bakatnya. Setelah itu ia harus berjuang keras untuk merawat potensinya itu dengan belajar sungguh-sungguh, memperbanyak latihan, mengasahnya agar semakin tajam. Kemudian ia mampu menggunakannya untuk mencapai tujuannya. Misalnya keinginan untuk kaya, terkenal, dan punya pekerjaan. Indikator: 1. Kesadaran Diri. 2. Rasa Syukur & Percaya Diri. 3. Perawatan Potensi. 4. Pengembangan Berkelanjutan. 5. Menggunakan potensi dengan baik. 6. Integrasi Nilai & Tujuan Hidup. 7. Evaluasi & Adaptasi."
24,"Jihad","Tiga kekuatan internal","Manusia sukses adalah mereka yang memiliki tiga kekuatan yang ada dalam dirinya yaitu : “Punya tujuan”, “Bisa berubah”, dan “Bisa mempertahankan perubahan tersebut.” Punya cita-cita yang tinggi adalah wujud dari berpikir besar. Cita-citanya tidak boleh hanya satu, sebab Allah memberikan banyak potensi pada diri manusia. Bisa berubah artinya, ia mampu meningkatkan dirinya. Bisa mempertahankan perubahan misalnya, ketika di ponten sholatnya sudah tertib dan khusuk, maka setelah di rumah kebiasaan itu tidak boleh hilang. Indikator: 1. Punya Tujuan. 2. Bisa Berubah. 3. Bisa Mempertahankan Perubahan. 4. Kesadaran Konsekuensi. 5. Integrasi Nilai Spiritual."
25,"Sabar","Sumpah SI 8  “Semua baik dan menjadi alat belajar.”","Mukmin sejati tak pernah menyalahkan orang lain atau keadaan atau alam atau Tuhan. Sebaliknya, mukmin sejati itu yang bersyukur tentang apapun yang terjadi. setiap musibah sebenarnya selalu ada hikmahnya. bahkan Imam Syafii pernah bersyukur dengan adanya neraka, sebab kata beliau, neraka membuatnya takut berbuat dosa. Misalnya kalau kita kecopetan itu artinya ; kita kurang sedekah, atau kita kurang berhati-hati. Maka bagi orang mukmin yang hebat, “Semua itu baik dan menjadi alat belajar.” Indikator: 1. Mindset Positif. 2. Fleksibel. 3. Kemampuan Refleksi. 4. Rasa Syukur. 5. Orientasi Belajar Seumur Hidup. 6. Integrasi Nilai Spiritual. 7. Ketahanan Emosional."
26,"Sabar","Sumpah SI 9 “Aku bagian dari masyarakat.”","Salah satu tujuan penciptaan adalah menjadi manusia yang bermanfaat, dan tak mungkin kita bisa bermanfaat dengan menjauhi masyarakat. Dari mana kita bisa mendapatkan pahala? Tanpa berinteraksi dengan masyarakat? Itu yang pertama, yang kedua adalah apakah kita bisa hidup tanpa masyarakat? Tanpa berinteraksi dengan orang lain? Tanpa hidup berdampingan dengan mereka ? manusia dirancang sebagai makhluk sosial, maka sudah menjadi kodratnya untuk hidup bersama. Indikator: 1. Rasa Memiliki. 2. Keterlibatan Sosial. 3. Tanggung Jawab Sosial. 4. Solidaritas & Empati. 5. Kemampuan Berkolaborasi. 6. Identitas Sosial Islami. 7. Orientasi Kontribusi."
27,"Sabar","Sumpah SI 10 “Aku sedang menulis kitabku sendiri.”","Allah yang maha perkasa saja menciptakan lauhil mahfudz untuk mencatat semua peristiwa. Allah menciptakan Roqib dan Atit sebagai malaikat yang bertugas khusus untuk mencatat kehidupan kita, baik buruknya perbuatan kita, dosa dan pahala yang kita lakukan. Maka mukmin yang serdas pasti meniru dengan membuat catatan hidupnya sendiri, boleh seperti diary, boleh dengan cara lainnya, bebas. Yang jelas kita harus mengawasi hidup kita dengan catatan itu. Indikator: 1. Kesadaran Diri. 2. Refleksi & Introspeksi. 3. Tanggung Jawab Spiritual. 4. Disiplin Mencatat Kehidupan. 5. Orientasi Perbaikan Diri. 6. Integrasi Ilmu & Amal. 7. Konsistensi & Kejujuran."
28,"Sabar","Empat suara di dalam diri","Suara malaikat, Suara syaithan, Suara kita yang pro dengan malaikat, dan suara kita yang pro syaithan. Di dalam diri kita terdapat empat suara. Suara pertama adalah suara malaikat, ia terletak di hati. Suara yang kedua adalah suara syaithan, ia bersarang di hawa nafsu/di otak bawah manusia. Suara ketiga adalah suara diri sendiri yang pro dengan malaikat akal dan hati. Sedangkan suara keempat adalah suara diri kita sendiri yang pro dengan syaithan, hawa nafsu, dan badan kita. Indikator: 1. Kesadaran Spiritual. 2. Kemampuan Membedakan Suara. 3. Kontrol Diri. 4. Kecenderungan pada Kebaikan. 5. Muhasabah (Introspeksi). 6. Integrasi dengan Nilai Agama. 7. Konsistensi dalam Latihan Jiwa."
29,"Sabar","Kontrol Diri","Manusia yang sukses adalah mereka yang memiliki kemampuan untuk mengendalikan diri, menahan godaan atau distraction yang merusak fokus. Implementasinya sangat luas. Dari yang terkecil misalnya menolak teman yang ngajak ngobrol di kelas, tidak melayani candaan teman di masjid ketika sholat. Sampai urusan besar seperti cita-cita. Misalnya cita-cita kita sebagai penghafal Quran, tapi hanya karena sulit dan bosan kita mudah berpaling dari tujuan utama lalu merubah cita-cita menjadi hanya ingin jadi pedagang. Padahal ia bisa jadi keduanya, yaitu jadi pedagang yang hafal Quran, namun urutannya tetap. Menghafal dulu, baru dagang. Indikator: 1. Kontrol Emosi & Nafsu. 2. Fokus pada Tujuan. 3. Disiplin dalam Rutinitas. 4. Kemampuan Menunda Kepuasan. 5. Kesadaran terhadap Distraksi. 6. Integrasi Spiritualitas. 7. Konsistensi & Istiqamah."
30,"Sabar","Mental Antisipatif (Daya tangkal)","Antispasi adalah daya menangkal masalah. Yaitu kemampuan meramalkan masalah dimasa depan, kemudian dibarengi dengan kemampuan merancang pencegahan, agar masalah itu tidak jadi muncul. Dan juga dibarengi dengan rancangan untuk menanganinya masalah itu seandainya masalah itu benar-benar muncul. Diimplementasikan ke semua urusan, dari yang sederhana misalnya sedia payung sebelum hujan, atau merancang evakuasi ketika terjadi tsunami. Indikator: 1. Kesadaran Situasi. 2. Perencanaan ke Depan. 3. Kesiapan Menghadapi Risiko. 4. Fleksibilitas & Adaptasi. 5. Proaktif. 6. Evaluasi Berkelanjutan. 7. Integrasi Nilai Spiritual."
31,"Sabar","Keseimbangan 4 waktu","Untuk mempertahankan prestasi kita harus menyeimbangkan 4 waktu : Time to pray, Time to learn, Time to rest, dan Time to play. Manusia butuh empat waktu dan empat asupan, yaitu waktu untuk beribadah, waktu untuk belajar, waktu untuk bermain, dan waktu untuk beristirahat. Apabila empat waktu ini tercukupi maka terbentuklah keseimbangan yang baik. Ketika kita beribadah kita tidak mengantuk, ketika kita belajar kita tidak bercanda, ketika jam tidur kita tidak scrol-scrol HP, di waktu tamasya kita malah sibuk bekerja. Indikator: 1. Time to Pray (Waktu untuk beribadah). 2. Time to Learn (Waktu untuk belajar). 3. Time to Rest (Waktu untuk istirahat). 4. Time to Play (Waktu untuk rekreasi/hiburan). 5. Kesadaran Prioritas. 6. Disiplin & Konsistensi. 7. Integrasi Nilai Spiritual."
32,"Sabar","Mental ITMI","Mental ITMI adalah kemampuan untuk menepis mudorotnya teknologi dan berfokus kepada manfaat teknologi. Islamic Technology Mindset Instalation (ITMI) berisi argumentasi logis dan syar’i yang menyampaikan bahwa teknologi itu hanyalah alat. Baik atau buruknya teknologi sangat bergantung kepada sang pembawanya, sama seperti pisau, ditangan perampok ia menjadi alat kejahatan. Tapi ditangan koki ia jadi alat untuk memasak makanan enak. Muslim sejati adalah mereka yang mampu menepis mudorotnya teknologi, dan mampu memanfaatkan teknologi untuk bisnis dan dakwah. Indikator: 1. Kesadaran Nilai. 2. Selektif dalam Penggunaan. 3. Orientasi Maslahat. 4. Kontrol Diri. 5. Literasi Digital. 6. Kreativitas Positif. 7. Integrasi Nilai Spiritual."
33,"Sabar","Mental menghargai karya sendiri","Kemampuan menghargai karya sendiri, mensyukuri pencapaian, bangga dengan jerih payah sendiri. Mental ini adalah faktor yang penting untuk menjadi manusia yang produktif. Apapun hasil dari ikhtiar yang maksimal harus disyukuri apapun bentuknya. mungkin tidak langsung bagus, tapi kalau kita terus memperbaikinya maka suatu saat pasti akan bagus. Justru kalau kita membenci karya sendiri, malu mengakui karya sendiri, perfeksionis di waktu yang salah, bisa berakibat membunuh produktivitas dan semakin memperparah kepercayaan dirimu. Membenci karya sendiri, selain buruk, itu merupakan perbuatan dosa (kufur nikmat). Menghargai karya sendiri artinya ; bangga dengan hasil capaian, terus mengevaluasi, dan terus menyempurnakannya. Indikator: 1. Rasa Syukur & Apresiasi. 2. Percaya Diri. 3. Tanggung Jawab terhadap Karya. 4. Konsistensi Berkarya. 5. Evaluasi & Perbaikan. 6. Integrasi Nilai Spiritual. 7. Orientasi Manfaat."
34,"Sabar","Konflik manajemen","Mental yang baik dalam mencegah dan menangani konflik adalah : Tabayun, Muhasabah, dan Isilah. Konflik manajemen adalah kemampuan mencegah dan menghadapi serta menangani konflik dengan baik. Pertama kita harus menghindari konflik, namun apabila memang harus, kita tidak takut berkonflik. Ini seperti prinsip perang kaum muslimin “kita tidak menginginkan perang, tapi tidak takut berperang kalau diperangi.” Yang kedua adalah kemampuan dalam menangani konflik. dengan tiga langkah, tabayun, muhasabah, dan ishlah. Tabayun adalah memastikan kebenaran informasi, konfirmasikan kepada pengucap asli, jangan berpegang kepada “Katanya” atau yang lebih buruk lagi “Asumsi”. Muhasabah adalah mencari kesalahan diri sendiri, dan Ishlah adalah berbaikan. Idealnya semua konflik harus diakhiri dengan berbaikan, kembali berhubungan dengan baik. Bukan saling mengalahkan dan mematikan. Indikator: 1. Tabayun (Cek Kebenaran). 2. Muhasabah (Introspeksi). 3. Islah (Berbaikan). 4. Kedewasaan Emosi. 5. Orientasi Maslahat. 6. Integrasi Syariat." """

def process():
    softskill_data = parse_data(softskill_str, "softskill")
    karakter_data = parse_data(karakter_str, "karakter")
    mental_data = parse_data(mental_str, "mental")
    
    print("softskill_data = [")
    for item in softskill_data:
        print(f"        {item},")
    print("    ]")
    
    print("\nkarakter_data = [")
    for item in karakter_data:
        print(f"        {item},")
    print("    ]")
    
    print("\nmental_data = [")
    for item in mental_data:
        print(f"        {item},")
    print("    ]")

if __name__ == "__main__":
    process()
